-- Made with 'mini.colors' module of https://github.com/echasnovski/mini.nvim

if vim.g.colors_name ~= nil then vim.cmd('highlight clear') end
vim.g.colors_name = "material-oceanic"

-- Highlight groups
local hi = vim.api.nvim_set_hl

hi(0, "@attribute", { link = "DiffChange" })
hi(0, "@character.special", { link = "SpecialChar" })
hi(0, "@comment.error", { bg = "#ec4061", fg = "#546e7a" })
hi(0, "@comment.hint", { bg = "#b682d9", fg = "#546e7a" })
hi(0, "@comment.note", { bg = "#a0b8ee", fg = "#546e7a" })
hi(0, "@comment.todo", { link = "Comment" })
hi(0, "@comment.warning", { bg = "#eeba5a", fg = "#546e7a" })
hi(0, "@conditional", { link = "Conditional" })
hi(0, "@constant", { fg = "#ffcb6b" })
hi(0, "@constant.builtin", { fg = "#ffcb6b" })
hi(0, "@constant.macro", { fg = "#89ddff" })
hi(0, "@constructor", { fg = "#82aaff" })
hi(0, "@define", { link = "@keyword.directive" })
hi(0, "@diff.delta", { link = "DiffChange" })
hi(0, "@diff.minus", { link = "DiffDelete" })
hi(0, "@diff.plus", { link = "DiffAdd" })
hi(0, "@error", { link = "Error" })
hi(0, "@field", { fg = "#7c9ead" })
hi(0, "@function.builtin", { link = "Function" })
hi(0, "@function.call", { link = "Function" })
hi(0, "@function.macro", { link = "Function" })
hi(0, "@function.method", { link = "Function" })
hi(0, "@function.method.call", { link = "Function" })
hi(0, "@include", { link = "Include" })
hi(0, "@keyword", { fg = "#89ddff" })
hi(0, "@keyword.conditional", { link = "Conditional" })
hi(0, "@keyword.coroutine", { fg = "#89ddff", italic = true })
hi(0, "@keyword.directive", { fg = "#89ddff" })
hi(0, "@keyword.directive.define", { link = "@keyword.directive" })
hi(0, "@keyword.exception", { link = "Exception" })
hi(0, "@keyword.export", { link = "@keyword" })
hi(0, "@keyword.function", { link = "@keyword" })
hi(0, "@keyword.import", { link = "Include" })
hi(0, "@keyword.operator", { link = "@keyword" })
hi(0, "@keyword.repeat", { link = "Repeat" })
hi(0, "@keyword.return", { link = "@keyword" })
hi(0, "@keyword.storage", { fg = "#89ddff" })
hi(0, "@label", { fg = "#ffcb6b" })
hi(0, "@lsp.type.boolean", { link = "@boolean" })
hi(0, "@lsp.type.builtinType", { link = "@type.builtin" })
hi(0, "@lsp.type.class", { link = "@type" })
hi(0, "@lsp.type.comment", { link = "@comment" })
hi(0, "@lsp.type.enum", { link = "@type" })
hi(0, "@lsp.type.enumMember", { link = "@constant" })
hi(0, "@lsp.type.escapeSequence", { link = "@string.escape" })
hi(0, "@lsp.type.formatSpecifier", { link = "@punctuation" })
hi(0, "@lsp.type.interface", { link = "Identifier" })
hi(0, "@lsp.type.keyword", { link = "@keyword" })
hi(0, "@lsp.type.namespace", { link = "@module" })
hi(0, "@lsp.type.number", { link = "@number" })
hi(0, "@lsp.type.operator", { link = "@operator" })
hi(0, "@lsp.type.parameter", { link = "@variable.parameter" })
hi(0, "@lsp.type.property", { link = "@property" })
hi(0, "@lsp.type.selfKeyword", { link = "@variable.builtin" })
hi(0, "@lsp.type.typeAlias", { link = "@type" })
hi(0, "@lsp.type.unresolvedReference", { link = "@error" })
hi(0, "@lsp.typemod.class.defaultLibrary", { link = "@type.builtin" })
hi(0, "@lsp.typemod.enum.defaultLibrary", { link = "@type.builtin" })
hi(0, "@lsp.typemod.enumMember.defaultLibrary", { link = "@constant.builtin" })
hi(0, "@lsp.typemod.function.defaultLibrary", { link = "@function.builtin" })
hi(0, "@lsp.typemod.keyword.async", { link = "@keyword.coroutine" })
hi(0, "@lsp.typemod.macro.defaultLibrary", { link = "@function.builtin" })
hi(0, "@lsp.typemod.method.defaultLibrary", { link = "@function.builtin" })
hi(0, "@lsp.typemod.operator.injected", { link = "@operator" })
hi(0, "@lsp.typemod.string.injected", { link = "@string" })
hi(0, "@lsp.typemod.type.defaultLibrary", { link = "@type.builtin" })
hi(0, "@lsp.typemod.variable.defaultLibrary", { link = "@variable.builtin" })
hi(0, "@lsp.typemod.variable.injected", { link = "@variable" })
hi(0, "@macro", { fg = "#89ddff" })
hi(0, "@markup.danger", { fg = "#ff5370" })
hi(0, "@markup.emphasis", { italic = true })
hi(0, "@markup.environment", { fg = "#f07178" })
hi(0, "@markup.environment.name", { fg = "#f07178" })
hi(0, "@markup.heading", { bold = true, fg = "#89ddff" })
hi(0, "@markup.link", { link = "Tag" })
hi(0, "@markup.link.url", { fg = "#80cbc4" })
hi(0, "@markup.list", { link = "Special" })
hi(0, "@markup.list.checked", { fg = "#c3e88d" })
hi(0, "@markup.list.unchecked", {})
hi(0, "@markup.literal", { fg = "#c3e88d" })
hi(0, "@markup.math", { fg = "#82aaff" })
hi(0, "@markup.raw", { fg = "#c792ea" })
hi(0, "@markup.title", { bold = true, fg = "#89ddff" })
hi(0, "@markup.warning", { fg = "#ffcb6b" })
hi(0, "@method", { link = "Function" })
hi(0, "@method.call", { link = "Function" })
hi(0, "@module", { fg = "#ffcb6b" })
hi(0, "@namespace", { fg = "#ffcb6b" })
hi(0, "@number.float", { link = "Float" })
hi(0, "@parameter", { link = "Identifier" })
hi(0, "@preproc", { fg = "#89ddff" })
hi(0, "@property", { fg = "#7c9ead" })
hi(0, "@punctuation", { fg = "#89ddff" })
hi(0, "@punctuation.bracket", { fg = "#89ddff" })
hi(0, "@punctuation.delimiter", { fg = "#89ddff" })
hi(0, "@punctuation.special", { fg = "#89ddff" })
hi(0, "@repeat", { link = "Repeat" })
hi(0, "@storageclass", { fg = "#89ddff" })
hi(0, "@string.escape", { fg = "#7c9ead" })
hi(0, "@string.regex", { fg = "#ffcb6b" })
hi(0, "@string.regexp", { fg = "#ffcb6b" })
hi(0, "@string.special", { fg = "#7c9ead" })
hi(0, "@string.special.symbol", { fg = "#ffcb6b" })
hi(0, "@symbol", { fg = "#ffcb6b" })
hi(0, "@tag", { fg = "#f07178" })
hi(0, "@tag.attribute", { fg = "#c792ea" })
hi(0, "@tag.delimiter", { fg = "#89ddff" })
hi(0, "@text.diff.add", { link = "DiffAdd" })
hi(0, "@text.diff.delete", { link = "DiffDelete" })
hi(0, "@text.environment", { fg = "#f07178" })
hi(0, "@text.environment.name", { fg = "#f07178" })
hi(0, "@text.literal", { fg = "#c792ea" })
hi(0, "@text.math", { fg = "#82aaff" })
hi(0, "@text.reference", { link = "Tag" })
hi(0, "@text.strong", { bold = true })
hi(0, "@text.title", { bold = true, fg = "#89ddff" })
hi(0, "@text.todo.checked", { fg = "#c3e88d" })
hi(0, "@text.todo.unchecked", {})
hi(0, "@text.underline", { underline = true })
hi(0, "@text.uri", { fg = "#80cbc4" })
hi(0, "@type", { fg = "#c792ea" })
hi(0, "@type.builtin", { fg = "#c792ea" })
hi(0, "@type.definition", {})
hi(0, "@type.qualifier", { fg = "#89ddff" })
hi(0, "@variable", { link = "Identifier" })
hi(0, "@variable.builtin", { link = "@keyword" })
hi(0, "@variable.member", { fg = "#7c9ead" })
hi(0, "@variable.parameter", { link = "Identifier" })
hi(0, "Black", { fg = "#000000" })
hi(0, "Blue", { fg = "#82aaff" })
hi(0, "Boolean", { link = "Number" })
hi(0, "BuffetActiveBuffer", { bg = "#17282d", fg = "#b0bec5" })
hi(0, "BuffetActiveBufferActiveBuffer", { link = "BuffetActiveBuffer" })
hi(0, "BuffetActiveBufferBuffer", { link = "BuffetActiveBuffer" })
hi(0, "BuffetActiveBufferCurrentBuffer", { bg = "#00eb00", fg = "#999999" })
hi(0, "BuffetActiveBufferEnd", { link = "BuffetActiveBuffer" })
hi(0, "BuffetActiveBufferModActiveBuffer", { link = "BuffetActiveBuffer" })
hi(0, "BuffetActiveBufferModBuffer", { link = "BuffetActiveBuffer" })
hi(0, "BuffetActiveBufferModCurrentBuffer", { bg = "#00eb00", fg = "#999999" })
hi(0, "BuffetActiveBufferRightTrunc", { link = "BuffetActiveBuffer" })
hi(0, "BuffetActiveBufferTab", { bg = "#0000d8", fg = "#999999" })
hi(0, "BuffetBuffer", { bg = "#17282d", fg = "#b0bec5" })
hi(0, "BuffetBufferActiveBuffer", { link = "BuffetBuffer" })
hi(0, "BuffetBufferBuffer", { link = "BuffetBuffer" })
hi(0, "BuffetBufferCurrentBuffer", { bg = "#00eb00", fg = "#999999" })
hi(0, "BuffetBufferEnd", { link = "BuffetBuffer" })
hi(0, "BuffetBufferModActiveBuffer", { link = "BuffetBuffer" })
hi(0, "BuffetBufferModBuffer", { link = "BuffetBuffer" })
hi(0, "BuffetBufferModCurrentBuffer", { bg = "#00eb00", fg = "#999999" })
hi(0, "BuffetBufferRightTrunc", { link = "BuffetBuffer" })
hi(0, "BuffetBufferTab", { bg = "#0000d8", fg = "#999999" })
hi(0, "BuffetCurrentBuffer", { bg = "#a0aeb5", bold = true, fg = "#25363b" })
hi(0, "BuffetCurrentBufferActiveBuffer", { bg = "#898989", fg = "#00ff00" })
hi(0, "BuffetCurrentBufferBuffer", { bg = "#898989", fg = "#00ff00" })
hi(0, "BuffetCurrentBufferCurrentBuffer", { link = "BuffetCurrentBuffer" })
hi(0, "BuffetCurrentBufferEnd", { bg = "#898989", fg = "#00ff00" })
hi(0, "BuffetCurrentBufferModActiveBuffer", { bg = "#898989", fg = "#00ff00" })
hi(0, "BuffetCurrentBufferModBuffer", { bg = "#898989", fg = "#00ff00" })
hi(0, "BuffetCurrentBufferModCurrentBuffer", { link = "BuffetCurrentBuffer" })
hi(0, "BuffetCurrentBufferRightTrunc", { bg = "#898989", fg = "#00ff00" })
hi(0, "BuffetCurrentBufferTab", { bg = "#0000d8", fg = "#00ff00" })
hi(0, "BuffetEnd", { link = "BuffetBuffer" })
hi(0, "BuffetLeftTrunc", { link = "BuffetTrunc" })
hi(0, "BuffetLeftTruncActiveBuffer", { link = "BuffetLeftTrunc" })
hi(0, "BuffetLeftTruncBuffer", { link = "BuffetLeftTrunc" })
hi(0, "BuffetLeftTruncCurrentBuffer", { bg = "#00eb00", fg = "#999999" })
hi(0, "BuffetLeftTruncModActiveBuffer", { link = "BuffetLeftTrunc" })
hi(0, "BuffetLeftTruncModBuffer", { link = "BuffetLeftTrunc" })
hi(0, "BuffetLeftTruncModCurrentBuffer", { bg = "#00eb00", fg = "#999999" })
hi(0, "BuffetModActiveBuffer", { link = "BuffetActiveBuffer" })
hi(0, "BuffetModActiveBufferActiveBuffer", { link = "BuffetModActiveBuffer" })
hi(0, "BuffetModActiveBufferBuffer", { link = "BuffetModActiveBuffer" })
hi(0, "BuffetModActiveBufferCurrentBuffer", { bg = "#00eb00", fg = "#999999" })
hi(0, "BuffetModActiveBufferEnd", { link = "BuffetModActiveBuffer" })
hi(0, "BuffetModActiveBufferModActiveBuffer", { link = "BuffetModActiveBuffer" })
hi(0, "BuffetModActiveBufferModBuffer", { link = "BuffetModActiveBuffer" })
hi(0, "BuffetModActiveBufferModCurrentBuffer", { bg = "#00eb00", fg = "#999999" })
hi(0, "BuffetModActiveBufferRightTrunc", { link = "BuffetModActiveBuffer" })
hi(0, "BuffetModActiveBufferTab", { bg = "#0000d8", fg = "#999999" })
hi(0, "BuffetModBuffer", { link = "BuffetBuffer" })
hi(0, "BuffetModBufferActiveBuffer", { link = "BuffetModBuffer" })
hi(0, "BuffetModBufferBuffer", { link = "BuffetModBuffer" })
hi(0, "BuffetModBufferCurrentBuffer", { bg = "#00eb00", fg = "#999999" })
hi(0, "BuffetModBufferEnd", { link = "BuffetModBuffer" })
hi(0, "BuffetModBufferModActiveBuffer", { link = "BuffetModBuffer" })
hi(0, "BuffetModBufferModBuffer", { link = "BuffetModBuffer" })
hi(0, "BuffetModBufferModCurrentBuffer", { bg = "#00eb00", fg = "#999999" })
hi(0, "BuffetModBufferRightTrunc", { link = "BuffetModBuffer" })
hi(0, "BuffetModBufferTab", { bg = "#0000d8", fg = "#999999" })
hi(0, "BuffetModCurrentBuffer", { link = "BuffetCurrentBuffer" })
hi(0, "BuffetModCurrentBufferActiveBuffer", { bg = "#898989", fg = "#00ff00" })
hi(0, "BuffetModCurrentBufferBuffer", { bg = "#898989", fg = "#00ff00" })
hi(0, "BuffetModCurrentBufferCurrentBuffer", { link = "BuffetModCurrentBuffer" })
hi(0, "BuffetModCurrentBufferEnd", { bg = "#898989", fg = "#00ff00" })
hi(0, "BuffetModCurrentBufferModActiveBuffer", { bg = "#898989", fg = "#00ff00" })
hi(0, "BuffetModCurrentBufferModBuffer", { bg = "#898989", fg = "#00ff00" })
hi(0, "BuffetModCurrentBufferModCurrentBuffer", { link = "BuffetModCurrentBuffer" })
hi(0, "BuffetModCurrentBufferRightTrunc", { bg = "#898989", fg = "#00ff00" })
hi(0, "BuffetModCurrentBufferTab", { bg = "#0000d8", fg = "#00ff00" })
hi(0, "BuffetRightTrunc", { link = "BuffetTrunc" })
hi(0, "BuffetRightTruncEnd", { link = "BuffetRightTrunc" })
hi(0, "BuffetRightTruncTab", { bg = "#0000d8", fg = "#999999" })
hi(0, "BuffetTab", { bg = "#17282d", fg = "#b0bec5" })
hi(0, "BuffetTabActiveBuffer", { bg = "#898989", fg = "#0000ff" })
hi(0, "BuffetTabBuffer", { bg = "#898989", fg = "#0000ff" })
hi(0, "BuffetTabCurrentBuffer", { bg = "#00eb00", fg = "#0000ff" })
hi(0, "BuffetTabEnd", { bg = "#898989", fg = "#0000ff" })
hi(0, "BuffetTabLeftTrunc", { bg = "#898989", fg = "#0000ff" })
hi(0, "BuffetTabModActiveBuffer", { bg = "#898989", fg = "#0000ff" })
hi(0, "BuffetTabModBuffer", { bg = "#898989", fg = "#0000ff" })
hi(0, "BuffetTabModCurrentBuffer", { bg = "#00eb00", fg = "#0000ff" })
hi(0, "BuffetTabTab", { link = "BuffetTab" })
hi(0, "BuffetTrunc", { bg = "#17282d", fg = "#b0bec5" })
hi(0, "Character", { link = "Number" })
hi(0, "CmpItemAbbrDeprecatedDefault", { fg = "#546e7a" })
hi(0, "CmpItemKindClassDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindColorDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindConstantDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindConstructorDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindDefault", { fg = "#89ddff" })
hi(0, "CmpItemKindEnumDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindEnumMemberDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindEventDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindFieldDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindFileDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindFolderDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindFunctionDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindInterfaceDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindKeywordDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindMethodDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindModuleDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindOperatorDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindPropertyDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindReferenceDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindSnippetDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindStructDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindTextDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindTypeParameterDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindUnitDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindValueDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindVariableDefault", { link = "CmpItemKind" })
hi(0, "CodeiumSuggestion", { ctermfg = 244, fg = "#808080" })
hi(0, "ColorColumn", { bg = "#23373b" })
hi(0, "Comment", { fg = "#546e7a" })
hi(0, "Conceal", { fg = "#3e5f64" })
hi(0, "Conditional", { fg = "#c792ea" })
hi(0, "Constant", { fg = "#ffcb6b" })
hi(0, "CurSearch", { bg = "#eeba5a", bold = true, fg = "#25363b" })
hi(0, "Cursor", { bg = "#bd83c7", bold = true, fg = "#ffffff" })
hi(0, "CursorColumn", { link = "CursorLine" })
hi(0, "CursorInsert", { bg = "#9a36ab", fg = "#000000" })
hi(0, "CursorLine", { bg = "#23373b" })
hi(0, "CursorLineNr", { fg = "#11bba3" })
hi(0, "Cyan", { fg = "#89ddff" })
hi(0, "Debug", { fg = "#f07178" })
hi(0, "Delimiter", { fg = "#89ddff" })
hi(0, "DiagnosticError", { fg = "#ff5370" })
hi(0, "DiagnosticHint", { fg = "#c792ea" })
hi(0, "DiagnosticInformation", { fg = "#b0c9ff" })
hi(0, "DiagnosticUnderlineError", { sp = "#ff5370", undercurl = true })
hi(0, "DiagnosticUnderlineHint", { sp = "#c792ea", undercurl = true })
hi(0, "DiagnosticUnderlineInfo", { sp = "#b0c9ff", undercurl = true })
hi(0, "DiagnosticUnderlineWarn", { sp = "#ffcb6b", undercurl = true })
hi(0, "DiagnosticWarn", { fg = "#ffcb6b" })
hi(0, "DiffAdd", { fg = "#c3e88d", reverse = true })
hi(0, "DiffChange", { fg = "#82aaff" })
hi(0, "DiffDelete", { fg = "#f07178", reverse = true })
hi(0, "DiffText", { fg = "#82aaff", reverse = true })
hi(0, "Directory", { fg = "#82aaff" })
hi(0, "EndOfBuffer", { fg = "#3e5f64" })
hi(0, "Error", { bold = true, fg = "#ff5370" })
hi(0, "ErrorMsg", { fg = "#ff5370" })
hi(0, "Exception", { link = "Exception" })
hi(0, "FloatBorder", { bg = "#17282d", fg = "#355058" })
hi(0, "FloatShadow", { bg = "#414449", blend = 80, ctermbg = 0 })
hi(0, "FloatShadowThrough", { bg = "#414449", blend = 100, ctermbg = 0 })
hi(0, "FoldColumn", { fg = "#82aaff" })
hi(0, "Folded", { bg = "#0e1d21", fg = "#3e5f64", italic = true })
hi(0, "Function", { fg = "#82aaff" })
hi(0, "GitSignsStagedAdd", { fg = "#597b60" })
hi(0, "GitSignsStagedAddCul", { fg = "#597b60" })
hi(0, "GitSignsStagedAddLn", { fg = "#617446" })
hi(0, "GitSignsStagedAddNr", { fg = "#597b60" })
hi(0, "GitSignsStagedChange", { fg = "#467c7b" })
hi(0, "GitSignsStagedChangeCul", { fg = "#467c7b" })
hi(0, "GitSignsStagedChangeLn", { fg = "#41557f" })
hi(0, "GitSignsStagedChangeNr", { fg = "#467c7b" })
hi(0, "GitSignsStagedChangedelete", { fg = "#467c7b" })
hi(0, "GitSignsStagedChangedeleteCul", { fg = "#467c7b" })
hi(0, "GitSignsStagedChangedeleteLn", { fg = "#41557f" })
hi(0, "GitSignsStagedChangedeleteNr", { fg = "#467c7b" })
hi(0, "GitSignsStagedDelete", { fg = "#7f605c" })
hi(0, "GitSignsStagedDeleteCul", { fg = "#7f605c" })
hi(0, "GitSignsStagedDeleteNr", { fg = "#7f605c" })
hi(0, "GitSignsStagedTopdelete", { fg = "#7f605c" })
hi(0, "GitSignsStagedTopdeleteCul", { fg = "#7f605c" })
hi(0, "GitSignsStagedTopdeleteNr", { fg = "#7f605c" })
hi(0, "GitSignsStagedUntracked", { fg = "#597b60" })
hi(0, "GitSignsStagedUntrackedCul", { fg = "#597b60" })
hi(0, "GitSignsStagedUntrackedLn", { fg = "#617446" })
hi(0, "GitSignsStagedUntrackedNr", { fg = "#597b60" })
hi(0, "Green", { fg = "#c3e88d" })
hi(0, "Identifier", { fg = "#b0bec5" })
hi(0, "Ignore", { fg = "#3e5f64" })
hi(0, "IncSearch", { bg = "#ddeeee", bold = true, fg = "#25363b" })
hi(0, "Include", { link = "Macro" })
hi(0, "Keyword", { fg = "#c792ea" })
hi(0, "Label", { fg = "#c792ea" })
hi(0, "LineNr", { fg = "#426367" })
hi(0, "LspCodeLens", { fg = "#c792ea", italic = true, sp = "#c792ea" })
hi(0, "LspInfoBorder", { fg = "#355058" })
hi(0, "LspInlayHint", { fg = "#546e7a", italic = true })
hi(0, "LspReferenceText", { bg = "#2b4c56" })
hi(0, "Macro", { fg = "#89ddff" })
hi(0, "MatchParen", { bold = true, fg = "#ffcb6b" })
hi(0, "ModeMsg", { fg = "#11bba3" })
hi(0, "MoreMsg", { fg = "#11bba3" })
hi(0, "NeogitActiveItem", { bg = "#b54e55", bold = true, fg = "#25363b" })
hi(0, "NeogitBranch", { bold = true, fg = "#89ddff" })
hi(0, "NeogitBranchHead", { bold = true, fg = "#89ddff", underline = true })
hi(0, "NeogitChangeAdded", { bold = true, fg = "#a0be74", italic = true })
hi(0, "NeogitChangeCopied", { bold = true, fg = "#70b5d1", italic = true })
hi(0, "NeogitChangeDeleted", { bold = true, fg = "#d1445c", italic = true })
hi(0, "NeogitChangeModified", { bold = true, fg = "#70b5d1", italic = true })
hi(0, "NeogitChangeNewFile", { bold = true, fg = "#a0be74", italic = true })
hi(0, "NeogitChangeRenamed", { bold = true, fg = "#70b5d1", italic = true })
hi(0, "NeogitChangeUnmerged", { bold = true, fg = "#babcc2", italic = true })
hi(0, "NeogitChangeUpdated", { bold = true, fg = "#c75e64", italic = true })
hi(0, "NeogitCommitViewHeader", { bg = "#60a5c0", fg = "#25363b" })
hi(0, "NeogitDiffAdd", { bg = "#b3d77d", fg = "#a0be74" })
hi(0, "NeogitDiffAddCursor", { bg = "#1b2c31", fg = "#c3e88d" })
hi(0, "NeogitDiffAddHighlight", { bg = "#b3d77d", fg = "#c3e88d" })
hi(0, "NeogitDiffAdditions", { fg = "#a0be74" })
hi(0, "NeogitDiffContext", { bg = "#1b2c31" })
hi(0, "NeogitDiffContextCursor", { bg = "#1b2c31" })
hi(0, "NeogitDiffContextHighlight", { bg = "#25353a" })
hi(0, "NeogitDiffDelete", { bg = "#de6169", fg = "#d1445c" })
hi(0, "NeogitDiffDeleteCursor", { bg = "#1b2c31", fg = "#ff5370" })
hi(0, "NeogitDiffDeleteHighlight", { bg = "#de6169", fg = "#ff5370" })
hi(0, "NeogitDiffDeletions", { fg = "#d1445c" })
hi(0, "NeogitDiffHeader", { bg = "#2f3e42", bold = true, fg = "#89ddff" })
hi(0, "NeogitDiffHeaderHighlight", { bg = "#2f3e42", bold = true, fg = "#f07178" })
hi(0, "NeogitFilePath", { fg = "#89ddff", italic = true })
hi(0, "NeogitFloatHeader", { bg = "#17282d", bold = true })
hi(0, "NeogitFloatHeaderHighlight", { bg = "#25353a", bold = true, fg = "#89ddff" })
hi(0, "NeogitGraphAuthor", { fg = "#f07178" })
hi(0, "NeogitGraphBlue", { fg = "#89ddff" })
hi(0, "NeogitGraphBoldBlue", { bold = true, fg = "#89ddff" })
hi(0, "NeogitGraphBoldCyan", { bold = true, fg = "#89ddff" })
hi(0, "NeogitGraphBoldGray", { bold = true, fg = "#7c8689" })
hi(0, "NeogitGraphBoldGreen", { bold = true, fg = "#c3e88d" })
hi(0, "NeogitGraphBoldOrange", { bold = true, fg = "#f07178" })
hi(0, "NeogitGraphBoldPurple", { bold = true, fg = "#89ddff" })
hi(0, "NeogitGraphBoldRed", { bold = true, fg = "#ff5370" })
hi(0, "NeogitGraphBoldWhite", { bold = true, fg = "#fcfcfc" })
hi(0, "NeogitGraphBoldYellow", { bold = true, fg = "#e0e2ea" })
hi(0, "NeogitGraphCyan", { fg = "#89ddff" })
hi(0, "NeogitGraphGray", { fg = "#7c8689" })
hi(0, "NeogitGraphGreen", { fg = "#c3e88d" })
hi(0, "NeogitGraphOrange", { fg = "#f07178" })
hi(0, "NeogitGraphPurple", { fg = "#89ddff" })
hi(0, "NeogitGraphRed", { fg = "#ff5370" })
hi(0, "NeogitGraphWhite", { fg = "#fcfcfc" })
hi(0, "NeogitGraphYellow", { fg = "#e0e2ea" })
hi(0, "NeogitHunkHeader", { bg = "#6d777a", bold = true, fg = "#25363b" })
hi(0, "NeogitHunkHeaderCursor", { bg = "#8ed2ee", bold = true, fg = "#25363b" })
hi(0, "NeogitHunkHeaderHighlight", { bg = "#8ed2ee", bold = true, fg = "#25363b" })
hi(0, "NeogitHunkMergeHeader", { bg = "#6d777a", bold = true, fg = "#334348" })
hi(0, "NeogitHunkMergeHeaderCursor", { bg = "#60a5c0", bold = true, fg = "#25363b" })
hi(0, "NeogitHunkMergeHeaderHighlight", { bg = "#60a5c0", bold = true, fg = "#25363b" })
hi(0, "NeogitPopupActionKey", { fg = "#89ddff" })
hi(0, "NeogitPopupBold", { bold = true })
hi(0, "NeogitPopupConfigKey", { fg = "#89ddff" })
hi(0, "NeogitPopupOptionKey", { fg = "#89ddff" })
hi(0, "NeogitPopupSwitchKey", { fg = "#89ddff" })
hi(0, "NeogitRemote", { bold = true, fg = "#c3e88d" })
hi(0, "NeogitSectionHeader", { bold = true, fg = "#70b5d1" })
hi(0, "NeogitTagDistance", { fg = "#89ddff" })
hi(0, "NeogitTagName", { fg = "#e0e2ea" })
hi(0, "NeogitUnmergedInto", { bold = true, fg = "#70b5d1" })
hi(0, "NeogitUnpulledFrom", { bold = true, fg = "#70b5d1" })
hi(0, "NeogitUnpushedTo", { bold = true, fg = "#70b5d1" })
hi(0, "NeoscrollHiddenCursor", { blend = 100, reverse = true })
hi(0, "NonText", { fg = "#3e5f64" })
hi(0, "Normal", { bg = "#17282d", fg = "#b0bec5" })
hi(0, "NormalContrast", { bg = "#0e1d21", fg = "#b0bec5" })
hi(0, "NormalFloat", { bg = "#17282d", fg = "#b0bec5" })
hi(0, "NormalNC", { bg = "#17282d" })
hi(0, "NotifyDEBUGBorder", { fg = "#8b8b8b" })
hi(0, "NotifyDEBUGIcon", { fg = "#8b8b8b" })
hi(0, "NotifyDEBUGTitle", { fg = "#8b8b8b" })
hi(0, "NotifyERRORBorder", { fg = "#8a1f1f" })
hi(0, "NotifyERRORIcon", { fg = "#f70067" })
hi(0, "NotifyERRORTitle", { fg = "#f70067" })
hi(0, "NotifyINFOBorder", { fg = "#4f6752" })
hi(0, "NotifyINFOIcon", { fg = "#a9ff68" })
hi(0, "NotifyINFOTitle", { fg = "#a9ff68" })
hi(0, "NotifyTRACEBorder", { fg = "#4f3552" })
hi(0, "NotifyTRACEIcon", { fg = "#d484ff" })
hi(0, "NotifyTRACETitle", { fg = "#d484ff" })
hi(0, "NotifyWARNBorder", { fg = "#79491d" })
hi(0, "NotifyWARNIcon", { fg = "#f79000" })
hi(0, "NotifyWARNTitle", { fg = "#f79000" })
hi(0, "Number", { fg = "#f78c6c" })
hi(0, "NvimInternalError", { bg = "#e30000", ctermbg = 9, ctermfg = 9, fg = "#ff0000" })
hi(0, "NvimTreeFolderIcon", { ctermfg = 12, fg = "#8094b4" })
hi(0, "NvimTreeWindowPicker", { bg = "#3383b7", bold = true, ctermbg = 4, ctermfg = 15, fg = "#ededed" })
hi(0, "Operator", { fg = "#89ddff" })
hi(0, "Orange", { fg = "#f78c6c" })
hi(0, "Pmenu", { bg = "#274149", fg = "#b0bec5" })
hi(0, "PmenuSbar", { bg = "#23373b" })
hi(0, "PmenuSel", { bg = "#00a993", fg = "#1e272c" })
hi(0, "PmenuThumb", { fg = "#b0bec5" })
hi(0, "Purple", { fg = "#c792ea" })
hi(0, "Question", { fg = "#ffcb6b" })
hi(0, "QuickFixLine", { bg = "#ddeeee", fg = "#354a51", reverse = true })
hi(0, "RainbowDelimiterBlue", { ctermfg = 12, fg = "#458588" })
hi(0, "RainbowDelimiterCyan", { ctermfg = 14, fg = "#a89984" })
hi(0, "RainbowDelimiterGreen", { ctermfg = 10, fg = "#689d6a" })
hi(0, "RainbowDelimiterOrange", { ctermfg = 15, fg = "#d65d0e" })
hi(0, "RainbowDelimiterRed", { ctermfg = 9, fg = "#cc241d" })
hi(0, "RainbowDelimiterViolet", { ctermfg = 13, fg = "#b16286" })
hi(0, "RainbowDelimiterYellow", { ctermfg = 11, fg = "#d79921" })
hi(0, "Red", { fg = "#f07178" })
hi(0, "RedrawDebugClear", { bg = "#5a4500", ctermbg = 11, ctermfg = 0 })
hi(0, "RedrawDebugComposed", { bg = "#00441a", ctermbg = 10, ctermfg = 0 })
hi(0, "RedrawDebugRecompose", { bg = "#400004", ctermbg = 9, ctermfg = 0 })
hi(0, "Repeat", { fg = "#c792ea" })
hi(0, "Search", { bg = "#ddeeee", fg = "#25363b" })
hi(0, "SignColumn", { fg = "#b0bec5" })
hi(0, "SmoothCursor", { fg = "#ffd400" })
hi(0, "SmoothCursorAqua", { fg = "#00ffff" })
hi(0, "SmoothCursorBlue", { fg = "#0000ff" })
hi(0, "SmoothCursorGreen", { fg = "#008000" })
hi(0, "SmoothCursorOrange", { fg = "#ffa500" })
hi(0, "SmoothCursorPurple", { fg = "#800080" })
hi(0, "SmoothCursorRed", { fg = "#ff0000" })
hi(0, "SmoothCursorYellow", { fg = "#ffff00" })
hi(0, "Special", { fg = "#89ddff" })
hi(0, "SpecialChar", { fg = "#f07178" })
hi(0, "SpecialComment", { link = "Comment" })
hi(0, "SpecialKey", { fg = "#c792ea" })
hi(0, "SpellBad", { fg = "#f07178", italic = true, undercurl = true })
hi(0, "SpellCap", { fg = "#82aaff", italic = true, undercurl = true })
hi(0, "SpellLocal", { fg = "#89ddff", italic = true, undercurl = true })
hi(0, "SpellRare", { fg = "#c792ea", italic = true, undercurl = true })
hi(0, "Statement", { fg = "#89ddff" })
hi(0, "StatusLine", { bg = "#23373b", fg = "#b0bec5" })
hi(0, "StatusLineNC", { bg = "#17282d", fg = "#3e5f64" })
hi(0, "StatusLineTerm", { bg = "#23373b", fg = "#b0bec5" })
hi(0, "StatusLineTermNC", { bg = "#17282d", fg = "#3e5f64" })
hi(0, "StorageClass", { fg = "#89ddff" })
hi(0, "String", { fg = "#c3e88d" })
hi(0, "Structure", { fg = "#c792ea" })
hi(0, "TabLine", { fg = "#b0bec5" })
hi(0, "TabLineFill", { fg = "#b0bec5" })
hi(0, "TabLineSel", { bg = "#00a993", fg = "#25363b" })
hi(0, "Tag", { fg = "#f07178" })
hi(0, "TermCursor", { link = "Cursor" })
hi(0, "Title", { bold = true, fg = "#89ddff" })
hi(0, "Todo", { bold = true, fg = "#ffcb6b" })
hi(0, "TodoBgFIX", { bg = "#ec4061", bold = true, fg = "#25363b" })
hi(0, "TodoBgHACK", { bg = "#eeba5a", bold = true, fg = "#25363b" })
hi(0, "TodoBgNOTE", { bg = "#b682d9", bold = true, fg = "#25363b" })
hi(0, "TodoBgPERF", { bg = "#a0aeb5", bold = true, fg = "#25363b" })
hi(0, "TodoBgTEST", { bg = "#a0aeb5", bold = true, fg = "#25363b" })
hi(0, "TodoBgTODO", { bg = "#7ae7e6", bold = true, fg = "#25363b" })
hi(0, "TodoBgWARN", { bg = "#eeba5a", bold = true, fg = "#25363b" })
hi(0, "TodoFgFIX", { fg = "#ff5370" })
hi(0, "TodoFgHACK", { fg = "#ffcb6b" })
hi(0, "TodoFgNOTE", { fg = "#c792ea" })
hi(0, "TodoFgPERF", { fg = "#b0bec5" })
hi(0, "TodoFgTEST", { fg = "#b0bec5" })
hi(0, "TodoFgTODO", { fg = "#8cf8f7" })
hi(0, "TodoFgWARN", { fg = "#ffcb6b" })
hi(0, "TodoSignFIX", { fg = "#ff5370" })
hi(0, "TodoSignHACK", { fg = "#ffcb6b" })
hi(0, "TodoSignNOTE", { fg = "#c792ea" })
hi(0, "TodoSignPERF", { fg = "#b0bec5" })
hi(0, "TodoSignTEST", { fg = "#b0bec5" })
hi(0, "TodoSignTODO", { fg = "#8cf8f7" })
hi(0, "TodoSignWARN", { fg = "#ffcb6b" })
hi(0, "TreesitterContext", { bg = "#10181d" })
hi(0, "TreesitterContextLineNumber", { bg = "#10181d", fg = "#426367" })
hi(0, "Type", { fg = "#c792ea" })
hi(0, "Typedef", { fg = "#f07178" })
hi(0, "UfoFoldedBg", { bg = "#0e1d21" })
hi(0, "UfoFoldedFg", { fg = "#b0bec5" })
hi(0, "VertSplit", { fg = "#355058" })
hi(0, "Visual", { bg = "#2b4c56" })
hi(0, "WarningMsg", { fg = "#ffcb6b" })
hi(0, "Warnings", { fg = "#ffcb6b" })
hi(0, "Whitespace", { fg = "#3e5f64" })
hi(0, "WildMenu", { bold = true, fg = "#f78c6c" })
hi(0, "WinBar", { bg = "#000000", bold = true, fg = "#9b9ea4" })
hi(0, "WinBarNC", { bg = "#000000", fg = "#9b9ea4" })
hi(0, "WinSeparator", { fg = "#355058" })
hi(0, "Yellow", { fg = "#ffcb6b" })
hi(0, "ZenBg", { bg = "#152529", fg = "#233338" })
hi(0, "diffAdded", { fg = "#c3e88d" })
hi(0, "diffRemoved", { fg = "#f07178" })
hi(0, "healthError", { fg = "#ff5370" })
hi(0, "healthSuccess", { fg = "#c3e88d" })
hi(0, "healthWarning", { fg = "#ffcb6b" })
hi(0, "htmlLink", { fg = "#80cbc4", underline = true })
hi(0, "lCursor", { bg = "#a0aeb5", fg = "#25363b" })
hi(0, "lualine_a_filename_command", { bg = "#17282d", fg = "#546e7a" })
hi(0, "lualine_a_filename_inactive", { bg = "#17282d", fg = "#546e7a" })
hi(0, "lualine_a_filename_insert", { bg = "#17282d", fg = "#546e7a" })
hi(0, "lualine_a_filename_normal", { bg = "#17282d", fg = "#546e7a" })
hi(0, "lualine_a_filename_replace", { bg = "#17282d", fg = "#546e7a" })
hi(0, "lualine_a_filename_terminal", { bg = "#17282d", fg = "#546e7a" })
hi(0, "lualine_a_filename_visual", { bg = "#17282d", fg = "#546e7a" })
hi(0, "lualine_a_inactive", { bg = "#17282d", fg = "#546e7a" })
hi(0, "lualine_a_insert", { bg = "#b3d77d", bold = true, fg = "#25363b" })
hi(0, "lualine_a_normal", { bg = "#b682d9", bold = true, fg = "#25363b" })
hi(0, "lualine_a_replace", { bg = "#b682d9", bold = true, fg = "#25363b" })
hi(0, "lualine_a_visual", { bg = "#414449", bold = true, fg = "#b0bec5" })
hi(0, "lualine_b_filename", { bg = "#1f353a", fg = "#b0bec5" })
hi(0, "lualine_b_filename_command", { bg = "#1a2429", fg = "#b0bec5" })
hi(0, "lualine_b_filename_inactive", { bg = "#1a2429", fg = "#b0bec5" })
hi(0, "lualine_b_filename_insert", { bg = "#1a2429", fg = "#b0bec5" })
hi(0, "lualine_b_filename_normal", { bg = "#1a2429", fg = "#b0bec5" })
hi(0, "lualine_b_filename_replace", { bg = "#1a2429", fg = "#b0bec5" })
hi(0, "lualine_b_filename_terminal", { bg = "#1a2429", fg = "#b0bec5" })
hi(0, "lualine_b_filename_visual", { bg = "#1a2429", fg = "#b0bec5" })
hi(0, "lualine_b_inactive", { bg = "#17282d", fg = "#546e7a" })
hi(0, "lualine_b_normal", { bg = "#1a2429", fg = "#b0bec5" })
hi(0, "lualine_c_branch", { bg = "#b3d77d", fg = "#25363b" })
hi(0, "lualine_c_branch_command", { bg = "#b3d77d", fg = "#25363b" })
hi(0, "lualine_c_branch_inactive", { bg = "#b3d77d", fg = "#25363b" })
hi(0, "lualine_c_branch_insert", { bg = "#b3d77d", fg = "#25363b" })
hi(0, "lualine_c_branch_normal", { bg = "#b3d77d", fg = "#25363b" })
hi(0, "lualine_c_branch_replace", { bg = "#b3d77d", fg = "#25363b" })
hi(0, "lualine_c_branch_terminal", { bg = "#b3d77d", fg = "#25363b" })
hi(0, "lualine_c_branch_visual", { bg = "#b3d77d", fg = "#25363b" })
hi(0, "lualine_c_inactive", { bg = "#17282d", fg = "#546e7a" })
hi(0, "lualine_c_normal", { bg = "#17282d", fg = "#546e7a" })
hi(0, "lualine_transitional_lualine_a_normal_to_lualine_b_filename", { bg = "#1f353a", fg = "#c792ea" })
hi(0, "lualine_transitional_lualine_b_filename_to_lualine_c_branch", { bg = "#b3d77d", fg = "#2d4349" })
hi(0, "lualine_transitional_lualine_c_branch_to_lualine_c_normal", { bg = "#17282d", fg = "#c3e88d" })

-- Terminal colors
local g = vim.g

g.terminal_color_0 = "#000000"
g.terminal_color_1 = "#dc6068"
g.terminal_color_2 = "#abcf76"
g.terminal_color_3 = "#e6b455"
g.terminal_color_4 = "#6e98eb"
g.terminal_color_5 = "#b480d6"
g.terminal_color_6 = "#71c6e7"
g.terminal_color_7 = "#eeffff"
g.terminal_color_8 = "#3e5f64"
g.terminal_color_9 = "#f07178"
g.terminal_color_10 = "#c3e88d"
g.terminal_color_11 = "#ffcb6b"
g.terminal_color_12 = "#82aaff"
g.terminal_color_13 = "#c792ea"
g.terminal_color_14 = "#89ddff"
g.terminal_color_15 = "#eeffff"
