-- Made with 'mini.colors' module of https://github.com/echasnovski/mini.nvim

if vim.g.colors_name ~= nil then vim.cmd('highlight clear') end
vim.g.colors_name = "nord"

-- Highlight groups
local hi = vim.api.nvim_set_hl

hi(0, "@attribute", { fg = "#b48ead" })
hi(0, "@attribute.builtin", { link = "Special" })
hi(0, "@boolean", { bold = true, fg = "#81a1c1" })
hi(0, "@character", { fg = "#a3be8c", italic = true })
hi(0, "@character.special", { link = "SpecialChar" })
hi(0, "@comment", { fg = "#616e88", italic = true })
hi(0, "@comment.error", { link = "DiagnosticError" })
hi(0, "@comment.note", { link = "DiagnosticInfo" })
hi(0, "@comment.todo", { link = "Todo" })
hi(0, "@comment.warning", { link = "DiagnosticWarn" })
hi(0, "@conditional", { fg = "#81a1c1", italic = true })
hi(0, "@constant", { fg = "#ebcb8b" })
hi(0, "@constant.builtin", { bold = true, fg = "#8fbcbb" })
hi(0, "@constant.macro", { bold = true, fg = "#8fbcbb" })
hi(0, "@constructor", { fg = "#81a1c1" })
hi(0, "@diff.delta", { link = "Changed" })
hi(0, "@diff.minus", { link = "Removed" })
hi(0, "@diff.plus", { link = "Added" })
hi(0, "@error", { fg = "#bf616a" })
hi(0, "@exception", { fg = "#b48ead" })
hi(0, "@field", { fg = "#d8dee9", italic = true })
hi(0, "@float", { fg = "#b48ead" })
hi(0, "@function", { fg = "#88c0d0", italic = true })
hi(0, "@function.builtin", { fg = "#88c0d0", italic = true })
hi(0, "@funtion.macro", { fg = "#8fbcbb" })
hi(0, "@ibl.indent.char.1", { fg = "#3b4252" })
hi(0, "@ibl.scope.char.1", { fg = "#616e88", nocombine = true })
hi(0, "@ibl.scope.underline.1", { sp = "#616e88", underline = true })
hi(0, "@ibl.whitespace.char.1", { fg = "#3b4252" })
hi(0, "@include", { fg = "#81a1c1" })
hi(0, "@keyword", { fg = "#81a1c1", italic = true })
hi(0, "@keyword.function", { fg = "#88c0d0", italic = true })
hi(0, "@keyword.operator", { fg = "#88c0d0", italic = true })
hi(0, "@keyword.return", { fg = "#88c0d0", italic = true })
hi(0, "@label", { fg = "#b48ead" })
hi(0, "@lsp.mod.deprecated", { link = "DiagnosticDeprecated" })
hi(0, "@lsp.type.class", { link = "@type" })
hi(0, "@lsp.type.comment", { link = "@comment" })
hi(0, "@lsp.type.decorator", { link = "@attribute" })
hi(0, "@lsp.type.enum", { link = "@type" })
hi(0, "@lsp.type.enumMember", { link = "@constant" })
hi(0, "@lsp.type.event", { link = "@type" })
hi(0, "@lsp.type.function", { link = "@function" })
hi(0, "@lsp.type.interface", { link = "@type" })
hi(0, "@lsp.type.keyword", { link = "@keyword" })
hi(0, "@lsp.type.macro", { link = "@constant.macro" })
hi(0, "@lsp.type.method", { link = "@function.method" })
hi(0, "@lsp.type.modifier", { link = "@type.qualifier" })
hi(0, "@lsp.type.namespace", { link = "@module" })
hi(0, "@lsp.type.number", { link = "@number" })
hi(0, "@lsp.type.operator", { link = "@operator" })
hi(0, "@lsp.type.parameter", { link = "@variable.parameter" })
hi(0, "@lsp.type.property", { link = "@property" })
hi(0, "@lsp.type.regexp", { link = "@string.regexp" })
hi(0, "@lsp.type.string", { link = "@string" })
hi(0, "@lsp.type.struct", { link = "@type" })
hi(0, "@lsp.type.type", { link = "@type" })
hi(0, "@lsp.type.typeParameter", { link = "@type.definition" })
hi(0, "@lsp.type.variable", { link = "@variable" })
hi(0, "@markup.heading", { link = "Title" })
hi(0, "@markup.link", { link = "Underlined" })
hi(0, "@method", { fg = "#88c0d0", italic = true })
hi(0, "@module.builtin", { link = "Special" })
hi(0, "@namespace", { fg = "#d8dee9", italic = true })
hi(0, "@number", { fg = "#b48ead" })
hi(0, "@number.float", { link = "Float" })
hi(0, "@operator", { fg = "#81a1c1" })
hi(0, "@parameter", { fg = "#5e81ac" })
hi(0, "@property", { fg = "#5e81ac", italic = true })
hi(0, "@punctuation.bracket", { fg = "#88c0d0" })
hi(0, "@punctuation.delimiter", { fg = "#88c0d0" })
hi(0, "@punctuation.special", { fg = "#88c0d0" })
hi(0, "@repeat", { fg = "#81a1c1", italic = true })
hi(0, "@string", { fg = "#a3be8c", italic = true })
hi(0, "@string.escape", { fg = "#b48ead", italic = true })
hi(0, "@string.regex", { fg = "#8fbcbb", italic = true })
hi(0, "@string.regexp", { link = "@string.special" })
hi(0, "@string.special", { link = "SpecialChar" })
hi(0, "@string.special.url", { link = "Underlined" })
hi(0, "@symbol", { fg = "#b48ead" })
hi(0, "@tag", { fg = "#d8dee9" })
hi(0, "@tag.builtin", { link = "Special" })
hi(0, "@tag.delimiter", { fg = "#b48ead" })
hi(0, "@text", { fg = "#d8dee9" })
hi(0, "@text.emphasis", { fg = "#5e81ac", italic = true })
hi(0, "@text.literal", { fg = "#d8dee9" })
hi(0, "@text.math", { fg = "#8fbcbb" })
hi(0, "@text.reference", { bold = true, fg = "#b48ead" })
hi(0, "@text.strike", { fg = "#d8dee9", strikethrough = true })
hi(0, "@text.strong", { bold = true, fg = "#5e81ac" })
hi(0, "@text.title", { bold = true, fg = "#5e81ac" })
hi(0, "@text.underline", { fg = "#d8dee9", underline = true })
hi(0, "@text.uri", { fg = "#a3be8c", underline = true })
hi(0, "@type", { fg = "#81a1c1" })
hi(0, "@type.builtin", { fg = "#81a1c1" })
hi(0, "@variable", { bold = true, fg = "#d8dee9" })
hi(0, "@variable.builtin", { bold = true, fg = "#d8dee9" })
hi(0, "@variable.global", { bold = true, fg = "#d8dee9" })
hi(0, "@variable.parameter.builtin", { link = "Special" })
hi(0, "AerialArray", { fg = "#ebcb8b" })
hi(0, "AerialArrayIcon", { fg = "#ebcb8b" })
hi(0, "AerialBoolean", { bold = true, fg = "#81a1c1" })
hi(0, "AerialBooleanIcon", { bold = true, fg = "#81a1c1" })
hi(0, "AerialClass", { fg = "#81a1c1" })
hi(0, "AerialClassIcon", { fg = "#81a1c1" })
hi(0, "AerialConstant", { fg = "#ebcb8b" })
hi(0, "AerialConstantIcon", { fg = "#ebcb8b" })
hi(0, "AerialConstructor", { fg = "#81a1c1" })
hi(0, "AerialConstructorIcon", { fg = "#81a1c1" })
hi(0, "AerialEnum", { fg = "#81a1c1" })
hi(0, "AerialEnumIcon", { fg = "#81a1c1" })
hi(0, "AerialEnumMember", { fg = "#d8dee9" })
hi(0, "AerialEnumMemberIcon", { fg = "#d8dee9" })
hi(0, "AerialEvent", { fg = "#81a1c1" })
hi(0, "AerialEventIcon", { fg = "#81a1c1" })
hi(0, "AerialField", { fg = "#d8dee9" })
hi(0, "AerialFieldIcon", { fg = "#d8dee9" })
hi(0, "AerialFile", { fg = "#a3be8c" })
hi(0, "AerialFileIcon", { fg = "#a3be8c" })
hi(0, "AerialFunction", { fg = "#88c0d0" })
hi(0, "AerialFunctionIcon", { fg = "#88c0d0" })
hi(0, "AerialInterface", { fg = "#81a1c1" })
hi(0, "AerialInterfaceIcon", { fg = "#81a1c1" })
hi(0, "AerialKey", { fg = "#81a1c1" })
hi(0, "AerialKeyIcon", { fg = "#81a1c1" })
hi(0, "AerialLine", { bg = "#353e4f" })
hi(0, "AerialLineNC", { bg = "#353e4f" })
hi(0, "AerialMethod", { fg = "#8fbcbb" })
hi(0, "AerialMethodIcon", { fg = "#8fbcbb" })
hi(0, "AerialModule", { fg = "#d8dee9" })
hi(0, "AerialModuleIcon", { fg = "#d8dee9" })
hi(0, "AerialNamespace", { fg = "#d8dee9" })
hi(0, "AerialNamespaceIcon", { fg = "#d8dee9" })
hi(0, "AerialNull", { fg = "#81a1c1" })
hi(0, "AerialNullIcon", { fg = "#81a1c1" })
hi(0, "AerialNumber", { fg = "#b48ead" })
hi(0, "AerialNumberIcon", { fg = "#b48ead" })
hi(0, "AerialObject", { fg = "#81a1c1" })
hi(0, "AerialObjectIcon", { fg = "#81a1c1" })
hi(0, "AerialOperator", { fg = "#81a1c1" })
hi(0, "AerialOperatorIcon", { fg = "#81a1c1" })
hi(0, "AerialPackage", { fg = "#d8dee9" })
hi(0, "AerialPackageIcon", { fg = "#d8dee9" })
hi(0, "AerialProperty", { fg = "#5e81ac" })
hi(0, "AerialPropertyIcon", { fg = "#5e81ac" })
hi(0, "AerialString", { fg = "#a3be8c" })
hi(0, "AerialStringIcon", { fg = "#a3be8c" })
hi(0, "AerialStruct", { fg = "#81a1c1" })
hi(0, "AerialStructIcon", { fg = "#81a1c1" })
hi(0, "AerialTypeParameter", { fg = "#5e81ac" })
hi(0, "AerialTypeParameterIcon", { fg = "#5e81ac" })
hi(0, "AerialVariable", { bold = true, fg = "#d8dee9" })
hi(0, "AerialVariableIcon", { bold = true, fg = "#d8dee9" })
hi(0, "Boolean", { fg = "#81a1c1" })
hi(0, "BufferCurrent", { bg = "#2d3443" })
hi(0, "BufferCurrentIcon", { bg = "#2d3443" })
hi(0, "BufferCurrentIndex", { bg = "#2d3443" })
hi(0, "BufferCurrentMod", { bg = "#2d3443", fg = "#b48ead" })
hi(0, "BufferCurrentSign", { bg = "#2d3443" })
hi(0, "BufferCurrentTarget", { bg = "#2d3443", fg = "#bf616a" })
hi(0, "BufferInactive", { bg = "#202631", fg = "#4c566a" })
hi(0, "BufferInactiveIcon", { bg = "#202631", fg = "#4c566a" })
hi(0, "BufferInactiveIndex", { bg = "#202631", fg = "#4c566a" })
hi(0, "BufferInactiveMod", { bg = "#202631", fg = "#b48ead" })
hi(0, "BufferInactiveSign", { bg = "#202631", fg = "#4c566a" })
hi(0, "BufferInactiveTarget", { bg = "#202631", fg = "#bf616a" })
hi(0, "BufferLineBackground", { bg = "#141921", fg = "#616e88" })
hi(0, "BufferLineBuffer", { bg = "#141921", fg = "#616e88" })
hi(0, "BufferLineBufferSelected", { bg = "#202631", bold = true, fg = "#d8dee9", italic = true })
hi(0, "BufferLineBufferVisible", { bg = "#1c212b", fg = "#616e88" })
hi(0, "BufferLineCloseButton", { bg = "#141921", fg = "#616e88" })
hi(0, "BufferLineCloseButtonSelected", { bg = "#202631", fg = "#d8dee9" })
hi(0, "BufferLineCloseButtonVisible", { bg = "#1c212b", fg = "#616e88" })
hi(0, "BufferLineDevIconDefaultSelected", { bg = "#202631", fg = "#6d8086" })
hi(0, "BufferLineDiagnostic", { bg = "#141921", fg = "#485266" })
hi(0, "BufferLineDiagnosticSelected", { bg = "#202631", bold = true, fg = "#a2a6ae", italic = true })
hi(0, "BufferLineDiagnosticVisible", { bg = "#1c212b", fg = "#485266" })
hi(0, "BufferLineDuplicate", { bg = "#141921", fg = "#5c6881", italic = true })
hi(0, "BufferLineDuplicateSelected", { bg = "#202631", fg = "#5c6881", italic = true })
hi(0, "BufferLineDuplicateVisible", { bg = "#1c212b", fg = "#5c6881", italic = true })
hi(0, "BufferLineError", { bg = "#141921", fg = "#616e88", sp = "#bf616a" })
hi(0, "BufferLineErrorDiagnostic", { bg = "#141921", fg = "#485266", sp = "#8f484f" })
hi(0, "BufferLineErrorDiagnosticSelected", { bg = "#202631", bold = true, fg = "#8f484f", italic = true, sp = "#8f484f" })
hi(0, "BufferLineErrorDiagnosticVisible", { bg = "#1c212b", fg = "#485266" })
hi(0, "BufferLineErrorSelected", { bg = "#202631", bold = true, fg = "#bf616a", italic = true, sp = "#bf616a" })
hi(0, "BufferLineErrorVisible", { bg = "#1c212b", fg = "#616e88" })
hi(0, "BufferLineFill", { bg = "#0a0c13", fg = "#616e88" })
hi(0, "BufferLineGroupLabel", { bg = "#525f78", fg = "#191c23" })
hi(0, "BufferLineGroupSeparator", { bg = "#0a0c13", fg = "#616e88" })
hi(0, "BufferLineHint", { bg = "#141921", fg = "#616e88", sp = "#81a1c1" })
hi(0, "BufferLineHintDiagnostic", { bg = "#141921", fg = "#485266", sp = "#607890" })
hi(0, "BufferLineHintDiagnosticSelected", { bg = "#202631", bold = true, fg = "#607890", italic = true, sp = "#607890" })
hi(0, "BufferLineHintDiagnosticVisible", { bg = "#1c212b", fg = "#485266" })
hi(0, "BufferLineHintSelected", { bg = "#202631", bold = true, fg = "#81a1c1", italic = true, sp = "#81a1c1" })
hi(0, "BufferLineHintVisible", { bg = "#1c212b", fg = "#616e88" })
hi(0, "BufferLineIndicatorSelected", { bg = "#202631", fg = "#81a1c1" })
hi(0, "BufferLineIndicatorVisible", { bg = "#1c212b", fg = "#2a2f3a" })
hi(0, "BufferLineInfo", { bg = "#141921", fg = "#616e88", sp = "#5e81ac" })
hi(0, "BufferLineInfoDiagnostic", { bg = "#141921", fg = "#485266", sp = "#466081" })
hi(0, "BufferLineInfoDiagnosticSelected", { bg = "#202631", bold = true, fg = "#466081", italic = true, sp = "#466081" })
hi(0, "BufferLineInfoDiagnosticVisible", { bg = "#1c212b", fg = "#485266" })
hi(0, "BufferLineInfoSelected", { bg = "#202631", bold = true, fg = "#5e81ac", italic = true, sp = "#5e81ac" })
hi(0, "BufferLineInfoVisible", { bg = "#1c212b", fg = "#616e88" })
hi(0, "BufferLineModified", { bg = "#141921", fg = "#a3be8c" })
hi(0, "BufferLineModifiedSelected", { bg = "#202631", fg = "#a3be8c" })
hi(0, "BufferLineModifiedVisible", { bg = "#1c212b", fg = "#a3be8c" })
hi(0, "BufferLineNumbers", { bg = "#141921", fg = "#616e88" })
hi(0, "BufferLineNumbersSelected", { bg = "#202631", bold = true, fg = "#d8dee9", italic = true })
hi(0, "BufferLineNumbersVisible", { bg = "#1c212b", fg = "#616e88" })
hi(0, "BufferLineOffsetSeparator", { bg = "#0a0c13", fg = "#d8dee9" })
hi(0, "BufferLinePick", { bg = "#141921", bold = true, fg = "#bf616a", italic = true })
hi(0, "BufferLinePickSelected", { bg = "#202631", bold = true, fg = "#bf616a", italic = true })
hi(0, "BufferLinePickVisible", { bg = "#1c212b", bold = true, fg = "#bf616a", italic = true })
hi(0, "BufferLineSeparator", { bg = "#141921", fg = "#191c23" })
hi(0, "BufferLineSeparatorSelected", { bg = "#202631", fg = "#191c23" })
hi(0, "BufferLineSeparatorVisible", { bg = "#1c212b", fg = "#191c23" })
hi(0, "BufferLineTab", { bg = "#141921", fg = "#616e88" })
hi(0, "BufferLineTabClose", { bg = "#141921", fg = "#616e88" })
hi(0, "BufferLineTabSelected", { bg = "#202631", fg = "#81a1c1" })
hi(0, "BufferLineTabSeparator", { bg = "#141921", fg = "#191c23" })
hi(0, "BufferLineTabSeparatorSelected", { bg = "#202631", fg = "#191c23" })
hi(0, "BufferLineTruncMarker", { bg = "#0a0c13", fg = "#616e88" })
hi(0, "BufferLineWarning", { bg = "#141921", fg = "#616e88", sp = "#b48ead" })
hi(0, "BufferLineWarningDiagnostic", { bg = "#141921", fg = "#485266", sp = "#876a81" })
hi(0, "BufferLineWarningDiagnosticSelected", { bg = "#202631", bold = true, fg = "#876a81", italic = true, sp = "#876a81" })
hi(0, "BufferLineWarningDiagnosticVisible", { bg = "#1c212b", fg = "#485266" })
hi(0, "BufferLineWarningSelected", { bg = "#202631", bold = true, fg = "#b48ead", italic = true, sp = "#b48ead" })
hi(0, "BufferLineWarningVisible", { bg = "#1c212b", fg = "#616e88" })
hi(0, "BufferTabpageFill", { bg = "#202631" })
hi(0, "BufferVisible", { bg = "#353e4f" })
hi(0, "BufferVisibleIcon", { bg = "#353e4f" })
hi(0, "BufferVisibleIndex", { bg = "#353e4f" })
hi(0, "BufferVisibleMod", { bg = "#353e4f", fg = "#b48ead" })
hi(0, "BufferVisibleSign", { bg = "#353e4f" })
hi(0, "BufferVisibleTarget", { bg = "#353e4f", fg = "#bf616a" })
hi(0, "BuffetActiveBuffer", { bg = "#424852", ctermbg = 10, ctermfg = 2, fg = "#d8dee9" })
hi(0, "BuffetActiveBufferActiveBuffer", { link = "BuffetActiveBuffer" })
hi(0, "BuffetActiveBufferBuffer", { link = "BuffetActiveBuffer" })
hi(0, "BuffetActiveBufferCurrentBuffer", { bg = "#00eb00", fg = "#999999" })
hi(0, "BuffetActiveBufferEnd", { link = "BuffetActiveBuffer" })
hi(0, "BuffetActiveBufferModActiveBuffer", { link = "BuffetActiveBuffer" })
hi(0, "BuffetActiveBufferModBuffer", { link = "BuffetActiveBuffer" })
hi(0, "BuffetActiveBufferModCurrentBuffer", { bg = "#00eb00", fg = "#999999" })
hi(0, "BuffetActiveBufferRightTrunc", { link = "BuffetActiveBuffer" })
hi(0, "BuffetActiveBufferTab", { bg = "#0000d8", fg = "#999999" })
hi(0, "BuffetBuffer", { bg = "#202631", ctermbg = 10, ctermfg = 8, fg = "#d8dee9" })
hi(0, "BuffetBufferActiveBuffer", { link = "BuffetBuffer" })
hi(0, "BuffetBufferBuffer", { link = "BuffetBuffer" })
hi(0, "BuffetBufferCurrentBuffer", { bg = "#00eb00", fg = "#999999" })
hi(0, "BuffetBufferEnd", { link = "BuffetBuffer" })
hi(0, "BuffetBufferModActiveBuffer", { link = "BuffetBuffer" })
hi(0, "BuffetBufferModBuffer", { link = "BuffetBuffer" })
hi(0, "BuffetBufferModCurrentBuffer", { bg = "#00eb00", fg = "#999999" })
hi(0, "BuffetBufferRightTrunc", { link = "BuffetBuffer" })
hi(0, "BuffetBufferTab", { bg = "#0000d8", fg = "#999999" })
hi(0, "BuffetCurrentBuffer", { bg = "#c7cdd8", bold = true, ctermbg = 2, ctermfg = 8, fg = "#2e3440" })
hi(0, "BuffetCurrentBufferActiveBuffer", { bg = "#898989", fg = "#00ff00" })
hi(0, "BuffetCurrentBufferBuffer", { bg = "#898989", fg = "#00ff00" })
hi(0, "BuffetCurrentBufferCurrentBuffer", { link = "BuffetCurrentBuffer" })
hi(0, "BuffetCurrentBufferEnd", { bg = "#898989", fg = "#00ff00" })
hi(0, "BuffetCurrentBufferModActiveBuffer", { bg = "#898989", fg = "#00ff00" })
hi(0, "BuffetCurrentBufferModBuffer", { bg = "#898989", fg = "#00ff00" })
hi(0, "BuffetCurrentBufferModCurrentBuffer", { link = "BuffetCurrentBuffer" })
hi(0, "BuffetCurrentBufferRightTrunc", { bg = "#898989", fg = "#00ff00" })
hi(0, "BuffetCurrentBufferTab", { bg = "#0000d8", fg = "#00ff00" })
hi(0, "BuffetEnd", { link = "BuffetBuffer" })
hi(0, "BuffetLeftTrunc", { link = "BuffetTrunc" })
hi(0, "BuffetLeftTruncActiveBuffer", { link = "BuffetLeftTrunc" })
hi(0, "BuffetLeftTruncBuffer", { link = "BuffetLeftTrunc" })
hi(0, "BuffetLeftTruncCurrentBuffer", { bg = "#00eb00", fg = "#999999" })
hi(0, "BuffetLeftTruncModActiveBuffer", { link = "BuffetLeftTrunc" })
hi(0, "BuffetLeftTruncModBuffer", { link = "BuffetLeftTrunc" })
hi(0, "BuffetLeftTruncModCurrentBuffer", { bg = "#00eb00", fg = "#999999" })
hi(0, "BuffetModActiveBuffer", { link = "BuffetActiveBuffer" })
hi(0, "BuffetModActiveBufferActiveBuffer", { link = "BuffetModActiveBuffer" })
hi(0, "BuffetModActiveBufferBuffer", { link = "BuffetModActiveBuffer" })
hi(0, "BuffetModActiveBufferCurrentBuffer", { bg = "#00eb00", fg = "#999999" })
hi(0, "BuffetModActiveBufferEnd", { link = "BuffetModActiveBuffer" })
hi(0, "BuffetModActiveBufferModActiveBuffer", { link = "BuffetModActiveBuffer" })
hi(0, "BuffetModActiveBufferModBuffer", { link = "BuffetModActiveBuffer" })
hi(0, "BuffetModActiveBufferModCurrentBuffer", { bg = "#00eb00", fg = "#999999" })
hi(0, "BuffetModActiveBufferRightTrunc", { link = "BuffetModActiveBuffer" })
hi(0, "BuffetModActiveBufferTab", { bg = "#0000d8", fg = "#999999" })
hi(0, "BuffetModBuffer", { link = "BuffetBuffer" })
hi(0, "BuffetModBufferActiveBuffer", { link = "BuffetModBuffer" })
hi(0, "BuffetModBufferBuffer", { link = "BuffetModBuffer" })
hi(0, "BuffetModBufferCurrentBuffer", { bg = "#00eb00", fg = "#999999" })
hi(0, "BuffetModBufferEnd", { link = "BuffetModBuffer" })
hi(0, "BuffetModBufferModActiveBuffer", { link = "BuffetModBuffer" })
hi(0, "BuffetModBufferModBuffer", { link = "BuffetModBuffer" })
hi(0, "BuffetModBufferModCurrentBuffer", { bg = "#00eb00", fg = "#999999" })
hi(0, "BuffetModBufferRightTrunc", { link = "BuffetModBuffer" })
hi(0, "BuffetModBufferTab", { bg = "#0000d8", fg = "#999999" })
hi(0, "BuffetModCurrentBuffer", { link = "BuffetCurrentBuffer" })
hi(0, "BuffetModCurrentBufferActiveBuffer", { bg = "#898989", fg = "#00ff00" })
hi(0, "BuffetModCurrentBufferBuffer", { bg = "#898989", fg = "#00ff00" })
hi(0, "BuffetModCurrentBufferCurrentBuffer", { link = "BuffetModCurrentBuffer" })
hi(0, "BuffetModCurrentBufferEnd", { bg = "#898989", fg = "#00ff00" })
hi(0, "BuffetModCurrentBufferModActiveBuffer", { bg = "#898989", fg = "#00ff00" })
hi(0, "BuffetModCurrentBufferModBuffer", { bg = "#898989", fg = "#00ff00" })
hi(0, "BuffetModCurrentBufferModCurrentBuffer", { link = "BuffetModCurrentBuffer" })
hi(0, "BuffetModCurrentBufferRightTrunc", { bg = "#898989", fg = "#00ff00" })
hi(0, "BuffetModCurrentBufferTab", { bg = "#0000d8", fg = "#00ff00" })
hi(0, "BuffetRightTrunc", { link = "BuffetTrunc" })
hi(0, "BuffetRightTruncEnd", { link = "BuffetRightTrunc" })
hi(0, "BuffetRightTruncTab", { bg = "#0000d8", fg = "#999999" })
hi(0, "BuffetTab", { bg = "#202631", ctermbg = 4, ctermfg = 8, fg = "#838994" })
hi(0, "BuffetTabActiveBuffer", { bg = "#898989", fg = "#0000ff" })
hi(0, "BuffetTabBuffer", { bg = "#898989", fg = "#0000ff" })
hi(0, "BuffetTabCurrentBuffer", { bg = "#00eb00", fg = "#0000ff" })
hi(0, "BuffetTabEnd", { bg = "#898989", fg = "#0000ff" })
hi(0, "BuffetTabLeftTrunc", { bg = "#898989", fg = "#0000ff" })
hi(0, "BuffetTabModActiveBuffer", { bg = "#898989", fg = "#0000ff" })
hi(0, "BuffetTabModBuffer", { bg = "#898989", fg = "#0000ff" })
hi(0, "BuffetTabModCurrentBuffer", { bg = "#00eb00", fg = "#0000ff" })
hi(0, "BuffetTabTab", { link = "BuffetTab" })
hi(0, "BuffetTrunc", { bg = "#202631", ctermbg = 11, ctermfg = 8, fg = "#d8dee9" })
hi(0, "Character", { fg = "#a3be8c" })
hi(0, "CmpItemAbbr", { fg = "#d8dee9" })
hi(0, "CmpItemAbbrDefault", { fg = "#d8dee9" })
hi(0, "CmpItemAbbrDeprecatedDefault", { fg = "#616e88" })
hi(0, "CmpItemAbbrMatch", { bold = true, fg = "#e5e9f0" })
hi(0, "CmpItemAbbrMatchDefault", { fg = "#d8dee9" })
hi(0, "CmpItemAbbrMatchFuzzy", { bold = true, fg = "#e5e9f0" })
hi(0, "CmpItemAbbrMatchFuzzyDefault", { fg = "#d8dee9" })
hi(0, "CmpItemKind", { fg = "#b48ead" })
hi(0, "CmpItemKindClassDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindColorDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindConstantDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindConstructorDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindDefault", { fg = "#d8dee9" })
hi(0, "CmpItemKindEnumDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindEnumMemberDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindEventDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindFieldDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindFileDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindFolderDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindFunctionDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindInterfaceDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindKeywordDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindMethodDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindModuleDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindOperatorDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindPropertyDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindReferenceDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindSnippetDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindStructDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindTextDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindTypeParameterDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindUnitDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindValueDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindVariableDefault", { link = "CmpItemKind" })
hi(0, "CmpItemMenu", { fg = "#a3be8c" })
hi(0, "CmpItemMenuDefault", { fg = "#d8dee9" })
hi(0, "CodeBlock", { bg = "#2d3443" })
hi(0, "CodeiumSuggestion", { ctermfg = 244, fg = "#808080" })
hi(0, "ColInLineDiagnostic", { link = "Comment" })
hi(0, "ColorColumn", { bg = "#2d3443" })
hi(0, "CommandMode", { fg = "#d8dee9", reverse = true })
hi(0, "Comment", { fg = "#616e88", italic = true })
hi(0, "Conceal", { bg = "#202631" })
hi(0, "Conditional", { fg = "#81a1c1", italic = true })
hi(0, "Constant", { fg = "#d8dee9" })
hi(0, "CopilotLabel", { fg = "#4c566a" })
hi(0, "CurSearch", { bg = "#ebcf84", ctermbg = 11, ctermfg = 0, fg = "#07080d" })
hi(0, "Cursor", { bg = "#bd83c7", bold = true, fg = "#ffffff" })
hi(0, "CursorColumn", { bg = "#2d3443" })
hi(0, "CursorIM", { fg = "#e5e9f0", reverse = true })
hi(0, "CursorInsert", { bg = "#9a36ab", fg = "#000000" })
hi(0, "CursorLine", { bg = "#2d3443" })
hi(0, "CursorLineNr", { fg = "#d8dee9" })
hi(0, "DapBreakpoint", { fg = "#a3be8c" })
hi(0, "DapStopped", { fg = "#b48ead" })
hi(0, "DapUIBreakpointsCurrentLine", { fg = "#88c0d0" })
hi(0, "DapUIBreakpointsInfo", { fg = "#88c0d0" })
hi(0, "DapUIBreakpointsLine", { fg = "#88c0d0" })
hi(0, "DapUIBreakpointsPath", { fg = "#88c0d0" })
hi(0, "DapUIDecoration", { fg = "#88c0d0" })
hi(0, "DapUIFloatBorder", { fg = "#88c0d0" })
hi(0, "DapUIFrameName", { fg = "#d8dee9" })
hi(0, "DapUILineNumber", { fg = "#88c0d0" })
hi(0, "DapUIModifiedValue", { fg = "#88c0d0" })
hi(0, "DapUIScope", { fg = "#88c0d0" })
hi(0, "DapUISource", { fg = "#81a1c1" })
hi(0, "DapUIStoppedThread", { fg = "#88c0d0" })
hi(0, "DapUIThread", { fg = "#88c0d0" })
hi(0, "DapUIType", { fg = "#81a1c1" })
hi(0, "DapUIValue", { fg = "#d8dee9" })
hi(0, "DapUIVariable", { fg = "#d8dee9" })
hi(0, "DapUIWatchesEmpty", { fg = "#bf616a" })
hi(0, "DapUIWatchesError", { fg = "#bf616a" })
hi(0, "DapUIWatchesValue", { fg = "#88c0d0" })
hi(0, "DashboardCenter", { fg = "#88c0d0" })
hi(0, "DashboardFooter", { fg = "#a3be8c", italic = true })
hi(0, "DashboardHeader", { fg = "#81a1c1" })
hi(0, "DashboardShortCut", { fg = "#8fbcbb" })
hi(0, "Debug", { fg = "#bf616a" })
hi(0, "Define", { fg = "#81a1c1" })
hi(0, "DefinitionArrow", { fg = "#88c0d0" })
hi(0, "DefinitionBorder", { bg = "#202631", fg = "#d8dee9" })
hi(0, "DefinitionCount", { fg = "#5e81ac" })
hi(0, "DefinitionFile", { bg = "#202631", fg = "#d8dee9" })
hi(0, "DefinitionIcon", { fg = "#8fbcbb" })
hi(0, "DefinitionSearch", { link = "Search" })
hi(0, "Definitions", { fg = "#b48ead" })
hi(0, "DefinitionsIcon", { fg = "#81a1c1" })
hi(0, "Delimiter", { fg = "#eceff4" })
hi(0, "DiagnosticError", { fg = "#bf616a" })
hi(0, "DiagnosticFloatingError", { link = "LspDiagnosticsFloatingError" })
hi(0, "DiagnosticFloatingHint", { link = "LspDiagnosticsFloatingHint" })
hi(0, "DiagnosticFloatingInfo", { link = "LspDiagnosticsFloatingInformation" })
hi(0, "DiagnosticFloatingWarn", { link = "LspDiagnosticsFloatingWarning" })
hi(0, "DiagnosticHint", { fg = "#81a1c1" })
hi(0, "DiagnosticInfo", { fg = "#5e81ac" })
hi(0, "DiagnosticInformation", { fg = "#5e81ac" })
hi(0, "DiagnosticLineCol", { fg = "#d8dee9" })
hi(0, "DiagnosticMap", { fg = "#b48ead" })
hi(0, "DiagnosticQuickFix", { fg = "#a3be8c" })
hi(0, "DiagnosticSignError", { link = "LspDiagnosticsSignError" })
hi(0, "DiagnosticSignHint", { link = "LspDiagnosticsSignHint" })
hi(0, "DiagnosticSignInfo", { link = "LspDiagnosticsSignInformation" })
hi(0, "DiagnosticSignWarn", { link = "LspDiagnosticsSignWarning" })
hi(0, "DiagnosticTruncateLine", { fg = "#d8dee9" })
hi(0, "DiagnosticUnderlineError", { sp = "#bf616a", undercurl = true })
hi(0, "DiagnosticUnderlineHint", { sp = "#5e81ac", undercurl = true })
hi(0, "DiagnosticUnderlineInfo", { sp = "#5e81ac", undercurl = true })
hi(0, "DiagnosticUnderlineWarn", { sp = "#b48ead", undercurl = true })
hi(0, "DiagnosticVirtualTextError", { link = "LspDiagnosticsVirtualTextError" })
hi(0, "DiagnosticVirtualTextHint", { link = "LspDiagnosticsVirtualTextHint" })
hi(0, "DiagnosticVirtualTextInfo", { link = "LspDiagnosticsVirtualTextInformation" })
hi(0, "DiagnosticVirtualTextWarn", { link = "LspDiagnosticsVirtualTextWarning" })
hi(0, "DiagnosticWarn", { fg = "#b48ead" })
hi(0, "DiagnosticWarning", { fg = "#b48ead" })
hi(0, "DiffAdd", { ctermbg = 10, ctermfg = 0, fg = "#a3be8c", reverse = true })
hi(0, "DiffChange", { fg = "#ebcb8b", reverse = true })
hi(0, "DiffDelete", { ctermfg = 9, fg = "#bf616a", reverse = true })
hi(0, "DiffText", { ctermbg = 14, ctermfg = 0, fg = "#b48ead", reverse = true })
hi(0, "Directory", { ctermfg = 14, fg = "#8fbcbb" })
hi(0, "DressingSelectIdx", { link = "Special" })
hi(0, "EndOfBuffer", { fg = "#3b4252" })
hi(0, "Error", { bold = true, ctermbg = 9, ctermfg = 0, fg = "#bf616a", underline = true })
hi(0, "ErrorMsg", { ctermfg = 9 })
hi(0, "Exception", { fg = "#81a1c1" })
hi(0, "FernBranchText", { fg = "#616e88" })
hi(0, "FinderParam", { fg = "#b48ead" })
hi(0, "FinderPreviewSearch", { link = "Search" })
hi(0, "FinderSpinner", { fg = "#88c0d0" })
hi(0, "FinderSpinnerBorder", { bg = "#202631", fg = "#d8dee9" })
hi(0, "FinderSpinnerTitle", { link = "Title" })
hi(0, "Float", { fg = "#b48ead" })
hi(0, "FloatBorder", { bg = "#202631", fg = "#d8dee9" })
hi(0, "FloatShadow", { bg = "#414449", blend = 80, ctermbg = 0 })
hi(0, "FloatShadowThrough", { bg = "#414449", blend = 100, ctermbg = 0 })
hi(0, "FoldColumn", { fg = "#8fbcbb" })
hi(0, "Folded", { fg = "#616e88", italic = true })
hi(0, "Function", { ctermfg = 14, fg = "#88c0d0", italic = true })
hi(0, "GitGutterAdd", { fg = "#a3be8c" })
hi(0, "GitGutterChange", { fg = "#ebcb8b" })
hi(0, "GitGutterDelete", { fg = "#bf616a" })
hi(0, "GitSignsAdd", { fg = "#a3be8c" })
hi(0, "GitSignsAddLn", { fg = "#a3be8c" })
hi(0, "GitSignsAddNr", { fg = "#a3be8c" })
hi(0, "GitSignsChange", { fg = "#ebcb8b" })
hi(0, "GitSignsChangeLn", { fg = "#ebcb8b" })
hi(0, "GitSignsChangeNr", { fg = "#ebcb8b" })
hi(0, "GitSignsCurrentLineBlame", { bold = true, fg = "#616e88" })
hi(0, "GitSignsDelete", { fg = "#bf616a" })
hi(0, "GitSignsDeleteLn", { fg = "#bf616a" })
hi(0, "GitSignsDeleteNr", { fg = "#bf616a" })
hi(0, "GitSignsStagedAdd", { fg = "#515f46" })
hi(0, "GitSignsStagedAddCul", { fg = "#515f46" })
hi(0, "GitSignsStagedAddLn", { fg = "#515f46" })
hi(0, "GitSignsStagedAddNr", { fg = "#515f46" })
hi(0, "GitSignsStagedChange", { fg = "#756545" })
hi(0, "GitSignsStagedChangeCul", { fg = "#756545" })
hi(0, "GitSignsStagedChangeLn", { fg = "#756545" })
hi(0, "GitSignsStagedChangeNr", { fg = "#756545" })
hi(0, "GitSignsStagedChangedelete", { fg = "#756545" })
hi(0, "GitSignsStagedChangedeleteCul", { fg = "#756545" })
hi(0, "GitSignsStagedChangedeleteLn", { fg = "#756545" })
hi(0, "GitSignsStagedChangedeleteNr", { fg = "#756545" })
hi(0, "GitSignsStagedDelete", { fg = "#5f3035" })
hi(0, "GitSignsStagedDeleteCul", { fg = "#5f3035" })
hi(0, "GitSignsStagedDeleteLn", { fg = "#5f3035" })
hi(0, "GitSignsStagedDeleteNr", { fg = "#5f3035" })
hi(0, "GitSignsStagedTopdelete", { fg = "#5f3035" })
hi(0, "GitSignsStagedTopdeleteCul", { fg = "#5f3035" })
hi(0, "GitSignsStagedTopdeleteNr", { fg = "#5f3035" })
hi(0, "Headline1", { bg = "#2f2e36", fg = "#d08770" })
hi(0, "Headline2", { bg = "#313439", fg = "#ebcb8b" })
hi(0, "Headline3", { bg = "#2b3339", fg = "#a3be8c" })
hi(0, "Headline4", { bg = "#28303d", fg = "#81a1c1" })
hi(0, "Headline5", { bg = "#2c2e3b", fg = "#b48ead" })
hi(0, "Headline6", { bg = "#2f3540", fg = "#d8dee9" })
hi(0, "HopNextKey", { bold = true, fg = "#d8dee9" })
hi(0, "HopNextKey1", { bold = true, fg = "#88c0d0" })
hi(0, "HopNextKey2", { fg = "#d8dee9" })
hi(0, "HopUnmatched", { fg = "#4c566a" })
hi(0, "IblIndent", { link = "NonText" })
hi(0, "IblScope", { fg = "#616e88" })
hi(0, "IblWhitespace", { link = "NonText" })
hi(0, "Identifier", { ctermfg = 12, fg = "#81a1c1", italic = true })
hi(0, "Ignore", { fg = "#3b4252" })
hi(0, "IlluminatedWordRead", { bg = "#3e475b" })
hi(0, "IlluminatedWordText", { bg = "#3e475b" })
hi(0, "IlluminatedWordWrite", { bg = "#3e475b" })
hi(0, "Implements", { fg = "#b48ead" })
hi(0, "ImplementsCount", { fg = "#5e81ac" })
hi(0, "ImplementsIcon", { fg = "#81a1c1" })
hi(0, "IncSearch", { bg = "#4f729c", fg = "#eceff4" })
hi(0, "Include", { fg = "#81a1c1" })
hi(0, "IndentBlanklineChar", { fg = "#4c566a" })
hi(0, "IndentBlanklineContextChar", { fg = "#5e81ac" })
hi(0, "InsertMode", { fg = "#a3be8c", reverse = true })
hi(0, "Keyword", { fg = "#81a1c1", italic = true })
hi(0, "LSOutlinePreviewBorder", { bg = "#202631", fg = "#d8dee9" })
hi(0, "Label", { fg = "#81a1c1" })
hi(0, "LeapLabelPrimary", { bg = "#daba7b", fg = "#2e3440", nocombine = true })
hi(0, "LeapLabelSecondary", { bg = "#a47e9d", fg = "#2e3440", nocombine = true })
hi(0, "LeapMatch", { fg = "#ebcb8b", nocombine = true, underline = true })
hi(0, "LightspeedGreyWash", { fg = "#616e88" })
hi(0, "LightspeedLabel", { bold = true, fg = "#88c0d0" })
hi(0, "LightspeedLabelDistant", { bold = true, fg = "#b48ead" })
hi(0, "LightspeedLabelDistantOverlapped", { bold = true, fg = "#b48ead", underline = true })
hi(0, "LightspeedLabelOverlapped", { bold = true, fg = "#88c0d0", underline = true })
hi(0, "LightspeedMaskedChar", { bg = "#353e4f", bold = true, fg = "#d8dee9" })
hi(0, "LightspeedOneCharMatch", { bold = true, fg = "#88c0d0", reverse = true })
hi(0, "LightspeedShortcut", { bold = true, fg = "#5e81ac" })
hi(0, "LightspeedShortcutOverlapped", { bold = true, fg = "#5e81ac", underline = true })
hi(0, "LightspeedUniqueChar", { bold = true, underline = true })
hi(0, "LightspeedUnlabeledMatch", { bg = "#2d3443", fg = "#d8dee9" })
hi(0, "LineNr", { fg = "#616e88" })
hi(0, "LspDiagnosticsDefaultError", { fg = "#bf616a" })
hi(0, "LspDiagnosticsDefaultHint", { fg = "#81a1c1" })
hi(0, "LspDiagnosticsDefaultInformation", { fg = "#5e81ac" })
hi(0, "LspDiagnosticsDefaultWarning", { fg = "#b48ead" })
hi(0, "LspDiagnosticsError", { fg = "#d08770" })
hi(0, "LspDiagnosticsFloatingError", { fg = "#bf616a" })
hi(0, "LspDiagnosticsFloatingHint", { fg = "#81a1c1" })
hi(0, "LspDiagnosticsFloatingInformation", { fg = "#5e81ac" })
hi(0, "LspDiagnosticsFloatingWarning", { fg = "#b48ead" })
hi(0, "LspDiagnosticsHint", { fg = "#81a1c1" })
hi(0, "LspDiagnosticsInformation", { fg = "#5e81ac" })
hi(0, "LspDiagnosticsSignError", { fg = "#bf616a" })
hi(0, "LspDiagnosticsSignHint", { fg = "#81a1c1" })
hi(0, "LspDiagnosticsSignInformation", { fg = "#5e81ac" })
hi(0, "LspDiagnosticsSignWarning", { fg = "#b48ead" })
hi(0, "LspDiagnosticsUnderlineError", { sp = "#bf616a", undercurl = true })
hi(0, "LspDiagnosticsUnderlineHint", { sp = "#5e81ac", undercurl = true })
hi(0, "LspDiagnosticsUnderlineInformation", { sp = "#5e81ac", undercurl = true })
hi(0, "LspDiagnosticsUnderlineWarning", { sp = "#b48ead", undercurl = true })
hi(0, "LspDiagnosticsVirtualTextError", { fg = "#bf616a" })
hi(0, "LspDiagnosticsVirtualTextHint", { fg = "#81a1c1" })
hi(0, "LspDiagnosticsVirtualTextInformation", { fg = "#5e81ac" })
hi(0, "LspDiagnosticsVirtualTextWarning", { fg = "#b48ead" })
hi(0, "LspDiagnosticsWarning", { fg = "#b48ead" })
hi(0, "LspFloatWinBorder", { bg = "#202631", fg = "#d8dee9" })
hi(0, "LspFloatWinNormal", { bg = "#202631", fg = "#d8dee9" })
hi(0, "LspReferenceRead", { bg = "#2d3443", fg = "#d8dee9" })
hi(0, "LspReferenceText", { bg = "#2d3443", fg = "#d8dee9" })
hi(0, "LspReferenceWrite", { bg = "#2d3443", fg = "#d8dee9" })
hi(0, "LspSagaAutoPreview", { fg = "#d8dee9" })
hi(0, "LspSagaBorderTitle", { link = "Title" })
hi(0, "LspSagaCodeActionBorder", { bg = "#202631", fg = "#d8dee9" })
hi(0, "LspSagaCodeActionContent", { fg = "#d8dee9" })
hi(0, "LspSagaCodeActionTitle", { link = "Title" })
hi(0, "LspSagaCodeActionTrunCateLine", { link = "LspSagaCodeActionBorder" })
hi(0, "LspSagaDefPreviewBorder", { bg = "#202631", fg = "#d8dee9" })
hi(0, "LspSagaDiagnosticBorder", { bg = "#202631", fg = "#d8dee9" })
hi(0, "LspSagaDiagnosticError", { link = "DiagnosticError" })
hi(0, "LspSagaDiagnosticHeader", { fg = "#d8dee9" })
hi(0, "LspSagaDiagnosticHint", { link = "DiagnosticHint" })
hi(0, "LspSagaDiagnosticInfo", { link = "DiagnosticInfo" })
hi(0, "LspSagaDiagnosticSource", { link = "Comment" })
hi(0, "LspSagaDiagnosticTruncateLine", { link = "LspSagaDiagnosticBorder" })
hi(0, "LspSagaDiagnosticWarn", { link = "DiagnosticWarn" })
hi(0, "LspSagaErrorTrunCateLine", { link = "DiagnosticError" })
hi(0, "LspSagaFinderSelection", { bg = "#353e4f", fg = "#eceff4" })
hi(0, "LspSagaHintTrunCateLine", { link = "DiagnosticHint" })
hi(0, "LspSagaHoverBorder", { bg = "#202631", fg = "#d8dee9" })
hi(0, "LspSagaHoverTrunCateLine", { link = "LspSagaHoverBorder" })
hi(0, "LspSagaInfoTrunCateLine", { link = "DiagnosticInfo" })
hi(0, "LspSagaLightBulb", { link = "DiagnosticSignHint" })
hi(0, "LspSagaLspFinderBorder", { bg = "#202631", fg = "#d8dee9" })
hi(0, "LspSagaRenameBorder", { bg = "#202631", fg = "#d8dee9" })
hi(0, "LspSagaRenameMatch", { bg = "#7291b0", fg = "#eceff4" })
hi(0, "LspSagaShTrunCateLine", { link = "LspSagaSignatureHelpBorder" })
hi(0, "LspSagaSignatureHelpBorder", { bg = "#202631", fg = "#d8dee9" })
hi(0, "LspSagaWarnTrunCateLine", { link = "DiagnosticWarn" })
hi(0, "LspTroubleCount", { bg = "#4f729c", fg = "#81a1c1" })
hi(0, "LspTroubleNormal", { bg = "#202631", fg = "#d8dee9" })
hi(0, "LspTroubleText", { fg = "#d8dee9" })
hi(0, "Macro", { fg = "#81a1c1" })
hi(0, "MatchParen", { bold = true, fg = "#b48ead" })
hi(0, "MiniCompletionActiveParameter", { underline = true })
hi(0, "MiniCursorword", { bg = "#3e475b" })
hi(0, "MiniCursorwordCurrent", { bg = "#3e475b" })
hi(0, "MiniIndentscopePrefix", { nocombine = true })
hi(0, "MiniIndentscopeSymbol", { fg = "#5e81ac" })
hi(0, "MiniJump", { bg = "#c7cdd8", fg = "#2e3440" })
hi(0, "MiniJump2dSpot", { bold = true, fg = "#d08770", nocombine = true })
hi(0, "MiniStarterCurrent", { nocombine = true })
hi(0, "MiniStarterFooter", { fg = "#a3be8c", italic = true })
hi(0, "MiniStarterHeader", { fg = "#81a1c1" })
hi(0, "MiniStarterInactive", { link = "Comment" })
hi(0, "MiniStarterItem", { link = "Normal" })
hi(0, "MiniStarterItemBullet", { fg = "#d8dee9" })
hi(0, "MiniStarterItemPrefix", { fg = "#b48ead" })
hi(0, "MiniStarterQuery", { fg = "#5e81ac" })
hi(0, "MiniStarterSection", { fg = "#d8dee9" })
hi(0, "MiniStatuslineDevinfo", { bg = "#353e4f", fg = "#d8dee9" })
hi(0, "MiniStatuslineFileinfo", { bg = "#353e4f", fg = "#d8dee9" })
hi(0, "MiniStatuslineFilename", { bg = "#2d3443", fg = "#d8dee9" })
hi(0, "MiniStatuslineInactive", { bg = "#202631", bold = true, fg = "#d8dee9" })
hi(0, "MiniStatuslineModeCommand", { bg = "#a47e9d", bold = true, fg = "#2e3440" })
hi(0, "MiniStatuslineModeInsert", { bg = "#c7cdd8", bold = true, fg = "#3b4252" })
hi(0, "MiniStatuslineModeNormal", { bg = "#7291b0", bold = true, fg = "#3b4252" })
hi(0, "MiniStatuslineModeOther", { bg = "#daba7b", bold = true, fg = "#2e3440" })
hi(0, "MiniStatuslineModeReplace", { bg = "#ae515b", bold = true, fg = "#2e3440" })
hi(0, "MiniStatuslineModeVisual", { bg = "#7facab", bold = true, fg = "#2e3440" })
hi(0, "MiniSurround", { link = "IncSearch" })
hi(0, "MiniTablineCurrent", { bg = "#2d3443" })
hi(0, "MiniTablineFill", { link = "TabLineFill" })
hi(0, "MiniTablineHidden", { bg = "#202631", fg = "#4c566a" })
hi(0, "MiniTablineModifiedCurrent", { bg = "#2d3443", fg = "#b48ead" })
hi(0, "MiniTablineModifiedHidden", { bg = "#202631", fg = "#b48ead" })
hi(0, "MiniTablineModifiedVisible", { bg = "#353e4f", fg = "#b48ead" })
hi(0, "MiniTablineTabpagesection", { bg = "#dbdee3", bold = true, fg = "#5e81ac", reverse = true })
hi(0, "MiniTablineVisible", { bg = "#353e4f" })
hi(0, "MiniTestEmphasis", { bold = true })
hi(0, "MiniTestFail", { bold = true, fg = "#bf616a" })
hi(0, "MiniTestPass", { bold = true, fg = "#a3be8c" })
hi(0, "MiniTrailspace", { bg = "#ae515b" })
hi(0, "ModeMsg", { ctermfg = 10, fg = "#d8dee9" })
hi(0, "MoreMsg", { ctermfg = 14, fg = "#d8dee9" })
hi(0, "MultiCursor", { link = "VM_Cursor" })
hi(0, "NavicIconsArray", { fg = "#ebcb8b" })
hi(0, "NavicIconsBoolean", { bold = true, fg = "#81a1c1" })
hi(0, "NavicIconsClass", { fg = "#81a1c1" })
hi(0, "NavicIconsConstant", { fg = "#ebcb8b" })
hi(0, "NavicIconsConstructor", { fg = "#81a1c1" })
hi(0, "NavicIconsEnum", { fg = "#81a1c1" })
hi(0, "NavicIconsEnumMember", { fg = "#d8dee9" })
hi(0, "NavicIconsEvent", { fg = "#81a1c1" })
hi(0, "NavicIconsField", { fg = "#d8dee9", italic = true })
hi(0, "NavicIconsFile", { fg = "#a3be8c" })
hi(0, "NavicIconsFunction", { fg = "#88c0d0", italic = true })
hi(0, "NavicIconsInterface", { fg = "#81a1c1" })
hi(0, "NavicIconsKey", { fg = "#81a1c1" })
hi(0, "NavicIconsMethod", { fg = "#8fbcbb", italic = true })
hi(0, "NavicIconsModule", { fg = "#d8dee9", italic = true })
hi(0, "NavicIconsNamespace", { fg = "#d8dee9", italic = true })
hi(0, "NavicIconsNull", { fg = "#81a1c1" })
hi(0, "NavicIconsNumber", { fg = "#b48ead" })
hi(0, "NavicIconsObject", { fg = "#81a1c1" })
hi(0, "NavicIconsOperator", { fg = "#81a1c1" })
hi(0, "NavicIconsPackage", { fg = "#d8dee9", italic = true })
hi(0, "NavicIconsProperty", { fg = "#d8dee9", italic = true })
hi(0, "NavicIconsString", { fg = "#a3be8c", italic = true })
hi(0, "NavicIconsStruct", { fg = "#81a1c1" })
hi(0, "NavicIconsTypeParameter", { fg = "#5e81ac" })
hi(0, "NavicIconsVariable", { bold = true, fg = "#d8dee9" })
hi(0, "NavicSeparator", { fg = "#d8dee9" })
hi(0, "NavicText", { fg = "#d8dee9" })
hi(0, "NeogitActiveItem", { bg = "#b39863", bold = true, fg = "#2e3440" })
hi(0, "NeogitBranch", { fg = "#5e81ac" })
hi(0, "NeogitBranchHead", { bold = true, fg = "#81a1c1", underline = true })
hi(0, "NeogitChangeAdded", { bold = true, fg = "#869c73", italic = true })
hi(0, "NeogitChangeCopied", { bold = true, fg = "#6a849e", italic = true })
hi(0, "NeogitChangeDeleted", { bold = true, fg = "#9d5057", italic = true })
hi(0, "NeogitChangeModified", { bold = true, fg = "#6a849e", italic = true })
hi(0, "NeogitChangeNewFile", { bold = true, fg = "#869c73", italic = true })
hi(0, "NeogitChangeRenamed", { bold = true, fg = "#6a849e", italic = true })
hi(0, "NeogitChangeUnmerged", { bold = true, fg = "#6b86a0", italic = true })
hi(0, "NeogitChangeUpdated", { bold = true, fg = "#c3a873", italic = true })
hi(0, "NeogitCommitViewHeader", { bg = "#5b758e", fg = "#2e3440" })
hi(0, "NeogitDiffAdd", { bg = "#93ae7c", fg = "#869c73" })
hi(0, "NeogitDiffAddCursor", { bg = "#242a35", fg = "#a3be8c" })
hi(0, "NeogitDiffAddHighlight", { fg = "#a3be8c", reverse = true })
hi(0, "NeogitDiffAdditions", { fg = "#869c73" })
hi(0, "NeogitDiffContext", { bg = "#242a35" })
hi(0, "NeogitDiffContextCursor", { bg = "#242a35" })
hi(0, "NeogitDiffContextHighlight", { bg = "#2d3443" })
hi(0, "NeogitDiffDelete", { bg = "#ae515b", fg = "#9d5057" })
hi(0, "NeogitDiffDeleteCursor", { bg = "#242a35", fg = "#bf616a" })
hi(0, "NeogitDiffDeleteHighlight", { fg = "#bf616a", reverse = true })
hi(0, "NeogitDiffDeletions", { fg = "#9d5057" })
hi(0, "NeogitDiffHeader", { bg = "#373c46", bold = true, fg = "#81a1c1" })
hi(0, "NeogitDiffHeaderHighlight", { bg = "#373c46", bold = true, fg = "#ebcb8b" })
hi(0, "NeogitFilePath", { fg = "#81a1c1", italic = true })
hi(0, "NeogitFloatHeader", { bg = "#202631", bold = true })
hi(0, "NeogitFloatHeaderHighlight", { bg = "#2e333d", bold = true, fg = "#81a1c1" })
hi(0, "NeogitGraphAuthor", { fg = "#ebcb8b" })
hi(0, "NeogitGraphBlue", { fg = "#81a1c1" })
hi(0, "NeogitGraphBoldBlue", { bold = true, fg = "#81a1c1" })
hi(0, "NeogitGraphBoldCyan", { bold = true, fg = "#81a1c1" })
hi(0, "NeogitGraphBoldGray", { bold = true, fg = "#82858c" })
hi(0, "NeogitGraphBoldGreen", { bold = true, fg = "#a3be8c" })
hi(0, "NeogitGraphBoldOrange", { bold = true, fg = "#ebcb8b" })
hi(0, "NeogitGraphBoldPurple", { bold = true, fg = "#81a1c1" })
hi(0, "NeogitGraphBoldRed", { bold = true, fg = "#bf616a" })
hi(0, "NeogitGraphBoldWhite", { bold = true, fg = "#fcfcfc" })
hi(0, "NeogitGraphBoldYellow", { bold = true, fg = "#81a1c1" })
hi(0, "NeogitGraphCyan", { fg = "#81a1c1" })
hi(0, "NeogitGraphGray", { fg = "#82858c" })
hi(0, "NeogitGraphGreen", { fg = "#a3be8c" })
hi(0, "NeogitGraphOrange", { fg = "#ebcb8b" })
hi(0, "NeogitGraphPurple", { fg = "#81a1c1" })
hi(0, "NeogitGraphRed", { fg = "#bf616a" })
hi(0, "NeogitGraphWhite", { fg = "#fcfcfc" })
hi(0, "NeogitGraphYellow", { fg = "#81a1c1" })
hi(0, "NeogitHunkHeader", { fg = "#88c0d0" })
hi(0, "NeogitHunkHeaderCursor", { bg = "#88a2bb", bold = true, fg = "#2e3440" })
hi(0, "NeogitHunkHeaderHighlight", { bg = "#2d3443", fg = "#88c0d0" })
hi(0, "NeogitHunkMergeHeader", { bg = "#73767c", bold = true, fg = "#3c414c" })
hi(0, "NeogitHunkMergeHeaderCursor", { bg = "#5b758e", bold = true, fg = "#2e3440" })
hi(0, "NeogitHunkMergeHeaderHighlight", { bg = "#5b758e", bold = true, fg = "#2e3440" })
hi(0, "NeogitPopupActionKey", { fg = "#81a1c1" })
hi(0, "NeogitPopupBold", { bold = true })
hi(0, "NeogitPopupConfigKey", { fg = "#81a1c1" })
hi(0, "NeogitPopupOptionKey", { fg = "#81a1c1" })
hi(0, "NeogitPopupSwitchKey", { fg = "#81a1c1" })
hi(0, "NeogitRemote", { fg = "#81a1c1" })
hi(0, "NeogitSectionHeader", { bold = true, fg = "#6a849e" })
hi(0, "NeogitTagDistance", { fg = "#81a1c1" })
hi(0, "NeogitTagName", { fg = "#81a1c1" })
hi(0, "NeogitUnmergedInto", { bold = true, fg = "#6a849e" })
hi(0, "NeogitUnpulledFrom", { bold = true, fg = "#6a849e" })
hi(0, "NeogitUnpushedTo", { bold = true, fg = "#6a849e" })
hi(0, "NeoscrollHiddenCursor", { blend = 100, reverse = true })
hi(0, "NonText", { fg = "#3b4252" })
hi(0, "Normal", { bg = "#202631", fg = "#d8dee9" })
hi(0, "NormalFloat", { bg = "#202631", fg = "#d8dee9" })
hi(0, "NormalMode", { fg = "#d8dee9", reverse = true })
hi(0, "NotifyDEBUGBorder", { fg = "#4c566a" })
hi(0, "NotifyDEBUGIcon", { fg = "#4c566a" })
hi(0, "NotifyDEBUGTitle", { fg = "#4c566a" })
hi(0, "NotifyERRORBorder", { fg = "#bf616a" })
hi(0, "NotifyERRORIcon", { fg = "#bf616a" })
hi(0, "NotifyERRORTitle", { fg = "#bf616a" })
hi(0, "NotifyINFOBody13", { bg = "#202631", fg = "#353b47" })
hi(0, "NotifyINFOBorder", { fg = "#a3be8c" })
hi(0, "NotifyINFOBorder13", { fg = "#333943" })
hi(0, "NotifyINFOIcon", { fg = "#a3be8c" })
hi(0, "NotifyINFOIcon13", { fg = "#333943" })
hi(0, "NotifyINFOTitle", { fg = "#a3be8c" })
hi(0, "NotifyINFOTitle13", { fg = "#333943" })
hi(0, "NotifyTRACEBorder", { fg = "#b48ead" })
hi(0, "NotifyTRACEIcon", { fg = "#b48ead" })
hi(0, "NotifyTRACETitle", { fg = "#b48ead" })
hi(0, "NotifyWARNBorder", { fg = "#ebcb8b" })
hi(0, "NotifyWARNIcon", { fg = "#ebcb8b" })
hi(0, "NotifyWARNTitle", { fg = "#ebcb8b" })
hi(0, "Number", { fg = "#b48ead" })
hi(0, "NvimInternalError", { bg = "#e30000", ctermbg = 9, ctermfg = 9, fg = "#ff0000" })
hi(0, "NvimSeparator", { bg = "#202631", fg = "#957cc6" })
hi(0, "NvimTreeEmptyFolderName", { fg = "#d8dee9" })
hi(0, "NvimTreeExecFile", { fg = "#d8dee9" })
hi(0, "NvimTreeFolderIcon", { fg = "#81a1c1" })
hi(0, "NvimTreeFolderName", { fg = "#d8dee9" })
hi(0, "NvimTreeGitDeleted", { fg = "#bf616a" })
hi(0, "NvimTreeGitDeletedIcon", { link = "NvimTreeGitDeleted" })
hi(0, "NvimTreeGitDirty", { fg = "#ebcb8b" })
hi(0, "NvimTreeGitDirtyIcon", { link = "NvimTreeGitDirty" })
hi(0, "NvimTreeGitIgnored", { fg = "#616e88" })
hi(0, "NvimTreeGitIgnoredIcon", { link = "NvimTreeGitIgnored" })
hi(0, "NvimTreeGitMerge", { fg = "#ebcb8b" })
hi(0, "NvimTreeGitMergeIcon", { link = "NvimTreeGitMerge" })
hi(0, "NvimTreeGitNew", { fg = "#a3be8c" })
hi(0, "NvimTreeGitNewIcon", { link = "NvimTreeGitNew" })
hi(0, "NvimTreeGitRenamed", { fg = "#ebcb8b" })
hi(0, "NvimTreeGitRenamedIcon", { link = "NvimTreeGitRenamed" })
hi(0, "NvimTreeGitStaged", { fg = "#ebcb8b" })
hi(0, "NvimTreeGitStagedIcon", { link = "NvimTreeGitStaged" })
hi(0, "NvimTreeImageFile", { fg = "#d8dee9" })
hi(0, "NvimTreeIndentMarker", { fg = "#81a1c1" })
hi(0, "NvimTreeMarkdownFile", { fg = "#d8dee9" })
hi(0, "NvimTreeNormal", { fg = "#d8dee9" })
hi(0, "NvimTreeOpenedFile", { fg = "#eceff4" })
hi(0, "NvimTreeOpenedFolderName", { fg = "#e5e9f0" })
hi(0, "NvimTreeOpenedHL", { link = "NvimTreeOpenedFile" })
hi(0, "NvimTreeRootFolder", { fg = "#b48ead" })
hi(0, "NvimTreeSpecialFile", { bold = true, fg = "#d8dee9" })
hi(0, "NvimTreeSymlink", { fg = "#e5e9f0" })
hi(0, "NvimTreeWindowPicker", { bg = "#3383b7", bold = true, ctermbg = 4, ctermfg = 15, fg = "#ededed" })
hi(0, "Operator", { fg = "#81a1c1" })
hi(0, "OutlineDetail", { fg = "#d8dee9" })
hi(0, "OutlineFoldPrefix", { fg = "#bf616a" })
hi(0, "OutlineIndentEvn", { fg = "#b48ead" })
hi(0, "OutlineIndentOdd", { fg = "#d08770" })
hi(0, "Pmenu", { bg = "#353e4f", fg = "#d8dee9" })
hi(0, "PmenuSbar", { bg = "#353e4f", fg = "#d8dee9" })
hi(0, "PmenuSel", { bg = "#4f729c", blend = 0, fg = "#d8dee9" })
hi(0, "PmenuThumb", { bg = "#c7cdd8", fg = "#d8dee9" })
hi(0, "PreCondit", { fg = "#ebcb8b" })
hi(0, "PreProc", { fg = "#81a1c1" })
hi(0, "Question", { ctermfg = 14, fg = "#a3be8c" })
hi(0, "QuickFixLine", { ctermfg = 14, fg = "#d8dee9", reverse = true })
hi(0, "Quote", { fg = "#434c5e" })
hi(0, "RainbowDelimiterBlue", { fg = "#81a1c1" })
hi(0, "RainbowDelimiterCyan", { fg = "#88c0d0" })
hi(0, "RainbowDelimiterGreen", { fg = "#a3be8c" })
hi(0, "RainbowDelimiterOrange", { fg = "#d08770" })
hi(0, "RainbowDelimiterRed", { fg = "#bf616a" })
hi(0, "RainbowDelimiterViolet", { fg = "#b48ead" })
hi(0, "RainbowDelimiterYellow", { fg = "#ebcb8b" })
hi(0, "RedrawDebugClear", { bg = "#5a4500", ctermbg = 11, ctermfg = 0 })
hi(0, "RedrawDebugComposed", { bg = "#00441a", ctermbg = 10, ctermfg = 0 })
hi(0, "RedrawDebugRecompose", { bg = "#400004", ctermbg = 9, ctermfg = 0 })
hi(0, "References", { fg = "#b48ead" })
hi(0, "ReferencesCount", { fg = "#5e81ac" })
hi(0, "ReferencesIcon", { fg = "#81a1c1" })
hi(0, "Repeat", { fg = "#81a1c1", italic = true })
hi(0, "ReplacelMode", { fg = "#bf616a", reverse = true })
hi(0, "SagaShadow", { fg = "#000000" })
hi(0, "Search", { bg = "#4f729c", ctermbg = 11, ctermfg = 0, fg = "#eceff4" })
hi(0, "SignColumn", { bg = "#202631", fg = "#d8dee9" })
hi(0, "SmoothCursor", { fg = "#ffd400" })
hi(0, "SmoothCursorAqua", { fg = "#00ffff" })
hi(0, "SmoothCursorBlue", { fg = "#0000ff" })
hi(0, "SmoothCursorGreen", { fg = "#008000" })
hi(0, "SmoothCursorOrange", { fg = "#ffa500" })
hi(0, "SmoothCursorPurple", { fg = "#800080" })
hi(0, "SmoothCursorRed", { fg = "#ff0000" })
hi(0, "SmoothCursorYellow", { fg = "#ffff00" })
hi(0, "Sneak", { bg = "#c7cdd8", fg = "#2e3440" })
hi(0, "SneakScope", { bg = "#2d3443" })
hi(0, "Special", { ctermfg = 14, fg = "#d8dee9" })
hi(0, "SpecialChar", { fg = "#ebcb8b" })
hi(0, "SpecialComment", { fg = "#88c0d0" })
hi(0, "SpecialKey", { fg = "#81a1c1" })
hi(0, "SpellBad", { fg = "#bf616a", italic = true, sp = "#ffc0b9", undercurl = true })
hi(0, "SpellCap", { fg = "#8fbcbb", italic = true, sp = "#fce094", undercurl = true })
hi(0, "SpellLocal", { fg = "#88c0d0", italic = true, sp = "#b3f6c0", undercurl = true })
hi(0, "SpellRare", { fg = "#81a1c1", italic = true, sp = "#8cf8f7", undercurl = true })
hi(0, "Statement", { fg = "#81a1c1" })
hi(0, "StatusLine", {})
hi(0, "StatusLineAccent", { bg = "#daba7b", fg = "#2e3440" })
hi(0, "StatusLineDull", { bg = "#2d3443", fg = "#4c566a" })
hi(0, "StatusLineNC", { bg = "#2d3443", fg = "#d8dee9" })
hi(0, "StatusLineTerm", { bg = "#353e4f", fg = "#d8dee9" })
hi(0, "StatusLineTermNC", { bg = "#2d3443", fg = "#d8dee9" })
hi(0, "StorageClass", { fg = "#81a1c1" })
hi(0, "String", { ctermfg = 10, fg = "#a3be8c", italic = true })
hi(0, "Structure", { fg = "#81a1c1" })
hi(0, "Substitute", { bg = "#bf7761", fg = "#2e3440" })
hi(0, "TSAnnotation", { fg = "#bf616a" })
hi(0, "TSAttribute", { fg = "#b48ead" })
hi(0, "TSBoolean", { bold = true, fg = "#81a1c1" })
hi(0, "TSCharacter", { fg = "#a3be8c", italic = true })
hi(0, "TSComment", { fg = "#616e88", italic = true })
hi(0, "TSConditional", { fg = "#81a1c1", italic = true })
hi(0, "TSConstBuiltin", { bold = true, fg = "#8fbcbb" })
hi(0, "TSConstMacro", { bold = true, fg = "#8fbcbb" })
hi(0, "TSConstant", { fg = "#ebcb8b" })
hi(0, "TSConstructor", { fg = "#81a1c1" })
hi(0, "TSEmphasis", { fg = "#5e81ac" })
hi(0, "TSError", { fg = "#bf616a" })
hi(0, "TSException", { fg = "#b48ead" })
hi(0, "TSField", { fg = "#d8dee9", italic = true })
hi(0, "TSFloat", { fg = "#b48ead" })
hi(0, "TSFuncBuiltin", { fg = "#88c0d0", italic = true })
hi(0, "TSFuncMacro", { fg = "#8fbcbb" })
hi(0, "TSFunction", { fg = "#88c0d0", italic = true })
hi(0, "TSInclude", { fg = "#81a1c1" })
hi(0, "TSKeyword", { fg = "#81a1c1", italic = true })
hi(0, "TSKeywordFunction", { fg = "#88c0d0", italic = true })
hi(0, "TSKeywordOperator", { fg = "#88c0d0", italic = true })
hi(0, "TSKeywordReturn", { fg = "#88c0d0", italic = true })
hi(0, "TSLabel", { fg = "#b48ead" })
hi(0, "TSLiteral", { fg = "#d8dee9" })
hi(0, "TSMethod", { fg = "#8fbcbb", italic = true })
hi(0, "TSNamespace", { fg = "#d8dee9", italic = true })
hi(0, "TSNumber", { fg = "#b48ead" })
hi(0, "TSOperator", { fg = "#81a1c1" })
hi(0, "TSParameter", { fg = "#5e81ac" })
hi(0, "TSParameterReference", { fg = "#5e81ac" })
hi(0, "TSProperty", { fg = "#5e81ac", italic = true })
hi(0, "TSPunctBracket", { fg = "#88c0d0" })
hi(0, "TSPunctDelimiter", { fg = "#88c0d0" })
hi(0, "TSPunctSpecial", { fg = "#88c0d0" })
hi(0, "TSRepeat", { fg = "#81a1c1", italic = true })
hi(0, "TSString", { fg = "#a3be8c", italic = true })
hi(0, "TSStringEscape", { fg = "#b48ead", italic = true })
hi(0, "TSStringRegex", { fg = "#8fbcbb", italic = true })
hi(0, "TSSymbol", { fg = "#b48ead" })
hi(0, "TSTag", { fg = "#d8dee9" })
hi(0, "TSTagDelimiter", { fg = "#b48ead" })
hi(0, "TSText", { fg = "#d8dee9" })
hi(0, "TSTextReference", { fg = "#b48ead" })
hi(0, "TSTitle", { bold = true, fg = "#5e81ac" })
hi(0, "TSType", { fg = "#81a1c1" })
hi(0, "TSTypeBuiltin", { fg = "#81a1c1" })
hi(0, "TSURI", { fg = "#a3be8c" })
hi(0, "TSUnderline", { fg = "#d8dee9", underline = true })
hi(0, "TSVariable", { bold = true, fg = "#d8dee9" })
hi(0, "TSVariableBuiltin", { bold = true, fg = "#d8dee9" })
hi(0, "TabLine", { bg = "#2d3443", fg = "#d8dee9" })
hi(0, "TabLineFill", { fg = "#d8dee9" })
hi(0, "TabLineSel", { bg = "#7291b0", fg = "#3b4252" })
hi(0, "Tag", { fg = "#d8dee9" })
hi(0, "TargetFileName", { fg = "#d8dee9" })
hi(0, "TargetWord", { bold = true, fg = "#eceff4" })
hi(0, "TelescopeMatching", { link = "Search" })
hi(0, "TelescopePreviewBorder", { fg = "#d8dee9" })
hi(0, "TelescopePromptBorder", { fg = "#d8dee9" })
hi(0, "TelescopeResultsBorder", { fg = "#d8dee9" })
hi(0, "TelescopeSelection", { bg = "#353e4f", fg = "#eceff4" })
hi(0, "TelescopeSelectionCaret", { fg = "#81a1c1" })
hi(0, "Title", { bold = true, fg = "#a3be8c" })
hi(0, "Todo", { bold = true, fg = "#ebcb8b", italic = true })
hi(0, "TodoBgFIX", { bg = "#ae515b", bold = true, fg = "#2e3440" })
hi(0, "TodoBgHACK", { bg = "#a47e9d", bold = true, fg = "#2e3440" })
hi(0, "TodoBgNOTE", { bg = "#7291b0", bold = true, fg = "#2e3440" })
hi(0, "TodoBgPERF", { bg = "#7291b0", bold = true, fg = "#2e3440" })
hi(0, "TodoBgTEST", { bg = "#7291b0", bold = true, fg = "#2e3440" })
hi(0, "TodoBgTODO", { bg = "#4f729c", bold = true, fg = "#2e3440" })
hi(0, "TodoBgWARN", { bg = "#a47e9d", bold = true, fg = "#2e3440" })
hi(0, "TodoFgFIX", { fg = "#bf616a" })
hi(0, "TodoFgHACK", { fg = "#b48ead" })
hi(0, "TodoFgNOTE", { fg = "#81a1c1" })
hi(0, "TodoFgPERF", { fg = "#81a1c1" })
hi(0, "TodoFgTEST", { fg = "#81a1c1" })
hi(0, "TodoFgTODO", { fg = "#5e81ac" })
hi(0, "TodoFgWARN", { fg = "#b48ead" })
hi(0, "TodoSignFIX", { bg = "#202631", fg = "#bf616a" })
hi(0, "TodoSignHACK", { bg = "#202631", fg = "#b48ead" })
hi(0, "TodoSignNOTE", { bg = "#202631", fg = "#81a1c1" })
hi(0, "TodoSignPERF", { bg = "#202631", fg = "#81a1c1" })
hi(0, "TodoSignTEST", { bg = "#202631", fg = "#81a1c1" })
hi(0, "TodoSignTODO", { bg = "#202631", fg = "#5e81ac" })
hi(0, "TodoSignWARN", { bg = "#202631", fg = "#b48ead" })
hi(0, "ToolbarButton", { bold = true, fg = "#d8dee9" })
hi(0, "ToolbarLine", { bg = "#2d3443", fg = "#d8dee9" })
hi(0, "Type", { fg = "#81a1c1" })
hi(0, "Typedef", { fg = "#81a1c1" })
hi(0, "UfoFoldedFg", { fg = "#d8dee9" })
hi(0, "Underlined", { fg = "#a3be8c", underline = true })
hi(0, "VertSplit", { fg = "#2e3440" })
hi(0, "Visual", { bg = "#353e4f", ctermbg = 15, ctermfg = 0 })
hi(0, "VisualMode", { fg = "#81a1c1", reverse = true })
hi(0, "VisualNOS", { bg = "#353e4f" })
hi(0, "WarningMsg", { ctermfg = 11, fg = "#b48ead" })
hi(0, "Warnings", { fg = "#b48ead" })
hi(0, "WhichKey", { bold = true, fg = "#88c0d0" })
hi(0, "WhichKeyDesc", { fg = "#8fbcbb", italic = true })
hi(0, "WhichKeyFloat", { bg = "#2d3443" })
hi(0, "WhichKeyFloating", { bg = "#2d3443" })
hi(0, "WhichKeyGroup", { fg = "#e5e9f0" })
hi(0, "WhichKeySeperator", { fg = "#81a1c1" })
hi(0, "WhichKeyValue", { fg = "#8fbcbb" })
hi(0, "WildMenu", { bold = true, fg = "#d08770" })
hi(0, "WinBar", { bg = "#000000", bold = true, fg = "#9b9ea4" })
hi(0, "WinBarNC", { bg = "#000000", fg = "#9b9ea4" })
hi(0, "ZenBg", { bg = "#1d232d", fg = "#2b313c" })
hi(0, "diffAdded", { fg = "#a3be8c" })
hi(0, "diffChanged", { fg = "#b48ead" })
hi(0, "diffFile", { fg = "#8fbcbb" })
hi(0, "diffIndexLine", { fg = "#81a1c1" })
hi(0, "diffLine", { fg = "#4c566a" })
hi(0, "diffNewFile", { fg = "#d08770" })
hi(0, "diffRemoved", { fg = "#bf616a" })
hi(0, "healthError", { fg = "#bf616a" })
hi(0, "healthSuccess", { fg = "#a3be8c" })
hi(0, "healthWarning", { fg = "#b48ead" })
hi(0, "htmlH1", { bold = true, fg = "#88c0d0" })
hi(0, "htmlH2", { bold = true, fg = "#bf616a" })
hi(0, "htmlH3", { bold = true, fg = "#a3be8c" })
hi(0, "htmlH4", { bold = true, fg = "#b48ead" })
hi(0, "htmlH5", { bold = true, fg = "#81a1c1" })
hi(0, "htmlLink", { fg = "#a3be8c", underline = true })
hi(0, "illuminatedCurWord", { bg = "#3e475b" })
hi(0, "illuminatedWord", { bg = "#3e475b" })
hi(0, "lCursor", { bg = "#c7cdd8", fg = "#2e3440" })
hi(0, "lualine_a_filename_command", { bg = "#202631", fg = "#616e88" })
hi(0, "lualine_a_filename_inactive", { bg = "#202631", fg = "#616e88" })
hi(0, "lualine_a_filename_insert", { bg = "#202631", fg = "#616e88" })
hi(0, "lualine_a_filename_normal", { bg = "#202631", fg = "#616e88" })
hi(0, "lualine_a_filename_replace", { bg = "#202631", fg = "#616e88" })
hi(0, "lualine_a_filename_terminal", { bg = "#202631", fg = "#616e88" })
hi(0, "lualine_a_filename_visual", { bg = "#202631", fg = "#616e88" })
hi(0, "lualine_a_inactive", { bg = "#202631", fg = "#616e88" })
hi(0, "lualine_a_insert", { bg = "#93ae7c", bold = true, fg = "#2e3440" })
hi(0, "lualine_a_normal", { bg = "#7291b0", bold = true, fg = "#2e3440" })
hi(0, "lualine_a_replace", { bg = "#7291b0", bold = true, fg = "#2e3440" })
hi(0, "lualine_a_visual", { bg = "#353e4f", bold = true, fg = "#d8dee9" })
hi(0, "lualine_b_filename", { bg = "#2a3240", fg = "#d8dee9" })
hi(0, "lualine_b_filename_command", { bg = "#2a3240", fg = "#d8dee9" })
hi(0, "lualine_b_filename_inactive", { bg = "#2a3240", fg = "#d8dee9" })
hi(0, "lualine_b_filename_insert", { bg = "#2a3240", fg = "#d8dee9" })
hi(0, "lualine_b_filename_normal", { bg = "#2a3240", fg = "#d8dee9" })
hi(0, "lualine_b_filename_replace", { bg = "#2a3240", fg = "#d8dee9" })
hi(0, "lualine_b_filename_terminal", { bg = "#2a3240", fg = "#d8dee9" })
hi(0, "lualine_b_filename_visual", { bg = "#2a3240", fg = "#d8dee9" })
hi(0, "lualine_b_inactive", { bg = "#202631", fg = "#616e88" })
hi(0, "lualine_b_normal", { bg = "#2a3240", fg = "#d8dee9" })
hi(0, "lualine_c_branch_command", { bg = "#93ae7c", fg = "#2e3440" })
hi(0, "lualine_c_branch_inactive", { bg = "#93ae7c", fg = "#2e3440" })
hi(0, "lualine_c_branch_insert", { bg = "#93ae7c", fg = "#2e3440" })
hi(0, "lualine_c_branch_normal", { bg = "#93ae7c", fg = "#2e3440" })
hi(0, "lualine_c_branch_replace", { bg = "#93ae7c", fg = "#2e3440" })
hi(0, "lualine_c_branch_terminal", { bg = "#93ae7c", fg = "#2e3440" })
hi(0, "lualine_c_branch_visual", { bg = "#93ae7c", fg = "#2e3440" })
hi(0, "lualine_c_inactive", { bg = "#202631", fg = "#616e88" })
hi(0, "lualine_c_normal", { bg = "#202631", fg = "#616e88" })
hi(0, "lualine_transitional_lualine_a_normal_to_StatusLine", { fg = "#81a1c1" })
hi(0, "lualine_transitional_lualine_a_normal_to_lualine_b_filename", { bg = "#2a3240", fg = "#81a1c1" })
hi(0, "lualine_transitional_lualine_b_filename_to_lualine_c_normal", { bg = "#202631", fg = "#38404f" })
hi(0, "markdownH1", { bold = true, fg = "#88c0d0" })
hi(0, "markdownH1Delimiter", { fg = "#88c0d0" })
hi(0, "markdownH2", { bold = true, fg = "#bf616a" })
hi(0, "markdownH2Delimiter", { fg = "#bf616a" })
hi(0, "markdownH3", { bold = true, fg = "#a3be8c" })
hi(0, "markdownH3Delimiter", { fg = "#a3be8c" })
hi(0, "qfLineNr", { fg = "#d8dee9", reverse = true })
hi(0, "rainbowcol1", { fg = "#b48ead" })
hi(0, "rainbowcol2", { fg = "#ebcb8b" })
hi(0, "rainbowcol3", { fg = "#bf616a" })
hi(0, "rainbowcol4", { fg = "#8fbcbb" })
hi(0, "rainbowcol5", { fg = "#88c0d0" })
hi(0, "rainbowcol6", { fg = "#b48ead" })
hi(0, "rainbowcol7", { fg = "#ebcb8b" })
hi(0, "yamlBlockMappingKey", { fg = "#8fbcbb" })
hi(0, "yamlBool", { link = "Boolean" })
hi(0, "yamlDocumentStart", { link = "Keyword" })
hi(0, "yamlKey", { fg = "#8fbcbb" })
hi(0, "yamlTSField", { fg = "#8fbcbb" })
hi(0, "yamlTSPunctSpecial", { link = "Keyword" })
hi(0, "yamlTSString", { fg = "#d8dee9" })

-- Terminal colors
local g = vim.g

g.terminal_color_0 = "#3b4252"
g.terminal_color_1 = "#bf616a"
g.terminal_color_2 = "#a3be8c"
g.terminal_color_3 = "#ebcb8b"
g.terminal_color_4 = "#81a1c1"
g.terminal_color_5 = "#b48ead"
g.terminal_color_6 = "#88c0d0"
g.terminal_color_7 = "#e5e9f0"
g.terminal_color_8 = "#4c566a"
g.terminal_color_9 = "#bf616a"
g.terminal_color_10 = "#a3be8c"
g.terminal_color_11 = "#ebcb8b"
g.terminal_color_12 = "#81a1c1"
g.terminal_color_13 = "#b48ead"
g.terminal_color_14 = "#8fbcbb"
g.terminal_color_15 = "#eceff4"
